"""
dispatch table generator for spu
requires cmd_dict file

specified format: DEF_CMD(name, num, ...)
"""

import sys

CMD_MAX_NUM = 255
DEFINE = "DEF_CMD"
LABEL_PREFIX = "cmd_dispatch_do_"
ERROR_LABEL = "cmd_dispatch_do_error"


labels = [0] * (CMD_MAX_NUM + 1)

if len(sys.argv) != 3:
    print("Specify input and output file!")
    exit(0)

inp = open(sys.argv[1], "r")

text = inp.read().replace(" ","").replace("\n","")

scope = 0
i = -1
while i < len(text) - 1:
    i += 1
    if text[i] == "(":
        scope += 1
        continue
    elif text[i] == ")":
        scope -= 1
        continue

    if scope == 0 and text[i:i + len(DEFINE) + 1] == DEFINE + "(":
        scope += 1
        i += len(DEFINE) + 1

        j = text.find(",", i)
        name = text[i:j]
        i = j + 1

        j = text.find(",", i)
        num = int(text[i:j])
        i = j

        labels[num] = name

inp.close()

out = open(sys.argv[2], "w")

out.write("/*This file was autogenerated by " + sys.argv[0] +
          " from " + sys.argv[1] + ". Do not edit!*/\n")

for i in labels:
    if i == 0:
        out.write("&&" + ERROR_LABEL + ",\n")
    else:
        out.write("&&" + LABEL_PREFIX + i + ",\n")

out.close()
