shared/lib/utils/args_parser.cpp File Reference
#include args_parser.h
Functions
Status::Statuses args_parse (int argc, char *argv[], ArgsVars *args_vars, const Argument args_dict[], const int args_dict_len)
Parses console arguments.
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int *arg_i, const int argc, char *argv[], ArgsVars *args_vars)
Prints help.
ArgsMode read_input_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Reads input file name from console.
ArgsMode read_output_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Reads output file name from console.
ArgsMode read_listing_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Reads debug file name from console.
ArgsMode enable_debug_mode (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Enables debug mode.
void print_commands_list ()
Prints commands list.
Function Documentation
args_parse()
Status::Statuses args_parse (int argc, char * argv[], ArgsVars * args_vars, const Argument args_dict[], const int args_dict_len)
Parses console arguments.
Parameters
 in argc
 in argv
 out args_vars
 in args_dict
 in args_dict_len
Returns
Status::Statuses
Definition at line 3 of file args_parser.cpp.
                                                                                 {
    assert(argv);
    assert(argc);
    assert(args_vars);
    bool exit = false;
    for (int i = 1; i < argc; i++) {
        bool is_found = false;
        for (int j = 0; j < args_dict_len; j++) {
            if (strcmp(argv[i], args_dict[j].arg) == 0) {
                switch (args_dict[j].func(args_dict, args_dict_len, &i, argc, argv, args_vars)) {
                    case ArgsMode::CONTINUE:
                        break;
                    case ArgsMode::EXIT:
                        exit = true;
                        break;
                    case ArgsMode::ERROR:
                        return Status::ARGS_ERROR;
                    default:
                        assert(0 && "args[j].func() returned wrong ArgsMode");
                        break;
                }
                is_found = true;
                break;
            }
        }
        if (is_found)
            continue;
        printf("Wrong console argument: %s\n"
               "Use -h for help\n", argv[i]);
        return Status::ARGS_ERROR;
    }
    if (exit)
        return Status::OK_EXIT;
    return Status::NORMAL_WORK;
}
References Status::ARGS_ERROR, CONTINUE, ERROR, EXIT, Status::NORMAL_WORK, and Status::OK_EXIT.
Referenced by main().
enable_debug_mode()
ArgsMode enable_debug_mode (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Enables debug mode.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 118 of file args_parser.cpp.
                                                                                    {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(args_vars);
    args_vars->debug_mode = true;
    return ArgsMode::CONTINUE;
}
References CONTINUE, and ArgsVars::debug_mode.
print_commands_list()
void print_commands_list ()
Prints commands list.
Definition at line 133 of file args_parser.cpp.
                           {
    printf("# Commands list:\n");
    for (size_t i = 0; i < CMDS_DICT_SIZE; i++) {
        const CmdInfo* cmd_info = CMDS_DICT + i;
        printf("# %3d) %-5s --- %s\n", cmd_info->num, cmd_info->name, cmd_info->description);
        if (cmd_info->args.reg || cmd_info->args.imm_double || cmd_info->args.imm_int
            || cmd_info->args.ram || cmd_info->args.label) {
            printf("# %3s%5s ", "", "");
            if (cmd_info->args.reg)
                printf(" <reg>");
            if (cmd_info->args.imm_double)
                printf(" <imm_double>");
            if (cmd_info->args.imm_int)
                printf(" <imm_int>");
            if (cmd_info->args.ram)
                printf(" <[]>");
            if (cmd_info->args.label)
                printf(" !label!");
            printf("\n");
        }
    }
}
References CmdInfo::args, CMDS_DICT, CMDS_DICT_SIZE, CmdInfo::description, ArgsEn::imm_double, ArgsEn::imm_int, ArgsEn::label, CmdInfo::name, CmdInfo::num, ArgsEn::ram, and ArgsEn::reg.
Referenced by print_help().
print_help()
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Prints help.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 in args_vars
Returns
ArgsMode
Definition at line 44 of file args_parser.cpp.
                                                                                   {
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(args_vars);
    printf("# Assembler, disassembler, SPU\n"
           "# Console args:\n");
    for (int i = 0; i < args_dict_len; i++)
        printf("%s", args_dict[i].description);
    print_commands_list();
    printf("# End of help\n");
    return ArgsMode::EXIT;
}
References EXIT, and print_commands_list().
read_input_filename()
ArgsMode read_input_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Reads input file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 64 of file args_parser.cpp.
                                                                                      {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argv);
    assert(args_vars);
    if (++(*arg_i) >= argc) {
        fprintf(stderr, "No input file name found\n");
        return ArgsMode::ERROR;
    }
    args_vars->input_filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsVars::input_filename.
read_listing_filename()
ArgsMode read_listing_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Reads debug file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 100 of file args_parser.cpp.
                                                                                        {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argv);
    assert(args_vars);
    if (++(*arg_i) >= argc) {
        fprintf(stderr, "No listing file name found\n");
        return ArgsMode::ERROR;
    }
    args_vars->listing_filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsVars::listing_filename.
read_output_filename()
ArgsMode read_output_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Reads output file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 82 of file args_parser.cpp.
                                                                                       {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argv);
    assert(args_vars);
    if (++(*arg_i) >= argc) {
        fprintf(stderr, "No output file name found\n");
        return ArgsMode::ERROR;
    }
    args_vars->output_filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsVars::output_filename.