assembler/src/assembler.cpp File Reference
#include assembler.h
Macros
#define LOCAL_DTOR_()
#define FILE_CHECK_(func_, ...)
#define THROW_SYNTAX_ERROR_(...)
Functions
Status::Statuses assemeble_and_write (const InputData *input_data, const char *bin_filename, const char *inp_filename, const char *listing_filename)
Assembles code and writes it to binary file. Listing file is optional.
Status::Statuses asm_parse_and_write_line (Buffer *buf, JumpLabel *labels, InputFileInfo *inp_file, const bool final_pass, FILE *listing_file)
Parses one line and writes to buf.
Macro Definition Documentation
FILE_CHECK_
#define FILE_CHECK_(func_, ...)
Value:
                                    do { \
                                    if (!func_) { \
                                        __VA_ARGS__; \
                                        return Status::OUT_FILE_ERROR; \
                                    } \
                                } while(0)
Definition at line 8 of file assembler.cpp.
LOCAL_DTOR_
#define LOCAL_DTOR_()
Value:
                            do { \
                            buf.dtor(); \
                        } while(0)
Definition at line 4 of file assembler.cpp.
THROW_SYNTAX_ERROR_
#define THROW_SYNTAX_ERROR_(...)
Value:
                                                                return asm_throw_syntax_error(tokens[cur_token], \
                                                                inp_file, \
                                                                __VA_ARGS__)
Definition at line 76 of file assembler.cpp.
Function Documentation
asm_parse_and_write_line()
Status::Statuses asm_parse_and_write_line (Buffer * buf, JumpLabel * labels, InputFileInfo * inp_file, const bool final_pass, FILE * listing_file = nullptr)
Parses one line and writes to buf.
Parameters
buf
labels
inp_file
final_pass
listing_file
Returns
Status::Statuses
Definition at line 80 of file assembler.cpp.
                                                                                     {
    assert(buf);
    assert(inp_file);
    assert(inp_file->filename);
    assert(inp_file->line.str);
    assert(labels);
    Cmd cmd = {};
    inp_file->comment = strchr(inp_file->line.str, ';');
    const char* special_delims = "[]:";
    String tokens[MAX_LINE_LEN + 1] = {};
    split_line_with_special_delims(inp_file->line.str, " +\t", special_delims, ";",
                                   tokens, MAX_LINE_LEN /*tokens array size*/);
    size_t cur_token = 0;
    // Empty line check
    if (tokens[cur_token].len == 0) {
        STATUS_CHECK(asm_write_cmd(buf, nullptr, labels, inp_file,
                                   listing_file, final_pass));
        return Status::NORMAL_WORK;
    }
    // Parsing start
    if (strchr(special_delims, tokens[cur_token].str[0]) != nullptr)
        THROW_SYNTAX_ERROR_("Unexpected '%c' found.", tokens[cur_token].str[0]);
    cmd.info = find_command_by_name(tokens[cur_token]);
    if (cmd.info == nullptr) {
        if (tokens[cur_token + 1].len >= 1 && tokens[cur_token + 1].str[0] == ':') {
            if (!final_pass)
                STATUS_CHECK(asm_new_label(labels, tokens[cur_token], inp_file, buf->size));
            cur_token += 2;
            inp_file->comment = str_skip_spaces(inp_file->line.str);
            STATUS_CHECK(asm_write_cmd(buf, nullptr, labels, inp_file,
                                       listing_file, final_pass));
            if (tokens[cur_token].str != nullptr)
                THROW_SYNTAX_ERROR_("Unexpected arg given.");
            return Status::NORMAL_WORK;
        } else
            THROW_SYNTAX_ERROR_("Command \"%.*s\" not found.", tokens[cur_token].len,
                                                               tokens[cur_token].str);
    }
    cmd.byte.num = cmd.info->num & CMD_BYTE_NUM_BIT_MASK;
    cur_token += 1;
    if (tokens[cur_token].str != nullptr && tokens[cur_token].len != 0) {
        if (strchr(special_delims, tokens[cur_token].str[0]) != nullptr) {
            if (tokens[cur_token].str[0] == '[') {
                cur_token++;
                STATUS_CHECK(asm_read_args_ram(tokens, &cur_token, &cmd, inp_file));
            } else
                THROW_SYNTAX_ERROR_("Unexpected '%c' found.", tokens[cur_token].str[0]);
        } else {
            STATUS_CHECK(asm_read_args(tokens, &cur_token, &cmd, inp_file, labels, final_pass));
        }
        if (tokens[cur_token].str != nullptr) //< read_args increments cur_token
            THROW_SYNTAX_ERROR_("Unexpected arg given.");
    }
    if (asm_is_arg_required(&cmd) && !(cmd.byte.imm || cmd.byte.ram || cmd.byte.reg))
        THROW_SYNTAX_ERROR_("At least one argument required.");
    STATUS_CHECK(asm_write_cmd(buf, &cmd, labels, inp_file, listing_file, final_pass));
    return Status::NORMAL_WORK;
}
References asm_is_arg_required(), asm_new_label(), asm_read_args(), asm_read_args_ram(), asm_write_cmd(), Cmd::byte, CMD_BYTE_NUM_BIT_MASK, InputFileInfo::comment, InputFileInfo::filename, find_command_by_name(), CmdByte::imm, Cmd::info, InputFileInfo::line, MAX_LINE_LEN, Status::NORMAL_WORK, CmdByte::num, CmdInfo::num, CmdByte::ram, CmdByte::reg, Buffer::size, split_line_with_special_delims(), STATUS_CHECK, String::str, str_skip_spaces(), and THROW_SYNTAX_ERROR_.
Referenced by assemeble_and_write().
assemeble_and_write()
Status::Statuses assemeble_and_write (const InputData * input_data, const char * bin_filename, const char * inp_filename, const char * listing_filename = nullptr)
Assembles code and writes it to binary file. Listing file is optional.
Parameters
input_data
bin_filename
inp_filename
listing_filename
Returns
Status::Statuses
Definition at line 15 of file assembler.cpp.
                                                                                             {
    assert(input_data);
    assert(bin_filename);
    assert(inp_filename);
    FILE* listing_file = nullptr;
    InputFileInfo inp_file = {{}, 0, nullptr, inp_filename};
    Buffer buf = {};
    if (!buf.ctor())
        return Status::MEMORY_EXCEED;
    JumpLabel labels[MAX_LABEL_NUM] = {};
    STATUS_CHECK(asm_write_header(&buf, listing_file, true), LOCAL_DTOR_());
    for (size_t i = 0; i < input_data->lines_cnt; i++) {
        inp_file.line_num = i + 1;
        inp_file.line = input_data->lines[i];
        STATUS_CHECK(asm_parse_and_write_line(&buf, labels, &inp_file, false, listing_file),
                     LOCAL_DTOR_());
    }
    // Second pass
    if (listing_filename != nullptr)
        FILE_CHECK_(file_open(&listing_file, listing_filename, "wb"), LOCAL_DTOR_());
    buf.size = 0;
    STATUS_CHECK(asm_write_header(&buf, listing_file, false), LOCAL_DTOR_());
    if (listing_filename != nullptr)
        if (file_printf(listing_file, ";line - byte - command\n") == EOF)
            return Status::OUT_FILE_ERROR;
    for (size_t i = 0; i < input_data->lines_cnt; i++) {
        inp_file.line_num = i + 1;
        inp_file.line = input_data->lines[i];
        STATUS_CHECK(asm_parse_and_write_line(&buf, labels, &inp_file, true, listing_file),
                     LOCAL_DTOR_());
    }
    if (listing_filename != nullptr)
        FILE_CHECK_(file_close(listing_file), LOCAL_DTOR_());
    // Binary file write
    STATUS_CHECK(file_open_write_bytes_close(bin_filename, buf.data, buf.size), LOCAL_DTOR_());
    LOCAL_DTOR_();
    return Status::NORMAL_WORK;
}
References asm_parse_and_write_line(), asm_write_header(), Buffer::ctor(), Buffer::data, FILE_CHECK_, file_close(), file_open(), file_open_write_bytes_close(), file_printf(), InputFileInfo::line, InputFileInfo::line_num, InputData::lines, InputData::lines_cnt, LOCAL_DTOR_, MAX_LABEL_NUM, Status::MEMORY_EXCEED, Status::NORMAL_WORK, Status::OUT_FILE_ERROR, Buffer::size, and STATUS_CHECK.
Referenced by main().