assembler/src/assembler.h File Reference
#include <math.h>
#include lib/utils/statuses.h
#include text/text_proccessor.h
#include lib/file/file.h
#include cmd.h
#include lib/utils/console.h
Functions
Status::Statuses assemeble_and_write (const InputData *input_data, const char *filename, bool debug_mode)
Assembles code and writes it to binary or text file.
Status::Statuses asm_parse_and_write_line (FILE *file, String line, const size_t line_num, bool debug_mode)
Parses and writes one line of code.
Status::Statuses asm_parse_is_arg_ram (char **str, Cmd *cmd, const size_t line_num)
Checks if [] are specified (ram arguments)
Status::Statuses asm_read_reg (const char *str, Cmd *cmd, const size_t line_num)
Reads cmd reg from str.
Status::Statuses asm_read_imm (const char *str, Cmd *cmd, const size_t line_num)
Reads cmd imm from str.
Status::Statuses asm_write_cmd_debug (FILE *file, const Cmd *cmd, const size_t binary_pos, const size_t line_num, const char *comment)
Writes cmd in text mode.
Status::Statuses asm_write_cmd_bin (FILE *file, const Cmd *cmd)
Writes cmd in binary mode.
Status::Statuses asm_write_cmd (FILE *file, const Cmd *cmd, size_t *binary_pos, const size_t line_num, const bool debug_mode, const char *comment)
Writes command to file.
Status::Statuses asm_write_signature (FILE *file, const bool debug_mode)
Writes signature to file.
bool asm_write_debug_comment (FILE *file, const char *comment)
Writes comment to listing file.
size_t asm_debug_calc_tab (const Cmd *cmd)
Calculates tab for debug listing.
Function Documentation
asm_debug_calc_tab()
size_t asm_debug_calc_tab (const Cmd * cmd) [inline]
Calculates tab for debug listing.
Parameters
cmd
Returns
size_t
Definition at line 127 of file assembler.h.
                                                 {
    size_t res = 0;
    if (cmd == nullptr)
        res += sizeof(cmd->byte) * 3;
    if (cmd == nullptr || !cmd->byte.reg)
        res += sizeof(cmd->args.reg) * 3;
    if (cmd == nullptr || !cmd->byte.imm)
        res += MAX(sizeof(cmd->args.imm), sizeof(cmd->args.imm_ram)) * 3;
    if (cmd != nullptr && cmd->byte.imm)
        if (sizeof(cmd->args.imm) < sizeof(cmd->args.imm_ram))
            res += (sizeof(cmd->args.imm_ram) - sizeof(cmd->args.imm)) * 3;
    if (cmd != nullptr && cmd->byte.ram)
        if (sizeof(cmd->args.imm_ram) < sizeof(cmd->args.imm))
            res += (sizeof(cmd->args.imm) - sizeof(cmd->args.imm_ram)) * 3;
    return res;
}
References Cmd::args, Cmd::byte, CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, MAX, CmdByte::ram, CmdByte::reg, and CmdArgs::reg.
Referenced by asm_write_cmd_debug().
asm_parse_and_write_line()
Status::Statuses asm_parse_and_write_line (FILE * file, String line, const size_t line_num, bool debug_mode)
Parses and writes one line of code.
Parameters
file
line
line_num
debug_mode
Returns
Status::Statuses
Definition at line 34 of file assembler.cpp.
                                                       {
    assert(file);
    assert(line.str);
    Cmd cmd = {};
    static size_t binary_pos = sizeof(SIGNATURE);
    char inp_buf[MAX_LINE_LEN] = {};
    const char* comment = text_throw_out_comment(line.str);
    line.str = strtok(line.str, " ");
    if (line.str == nullptr) { //< Empty line check
        STATUS_CHECK(asm_write_cmd(file, nullptr, &binary_pos, line_num, debug_mode, comment));
        return Status::NORMAL_WORK;
    }
    int res = sscanf(line.str, "%s", inp_buf);
    if (res != 1)
        THROW_SYNTAX_ERROR_("Can't read command name.");
    cmd.info = find_command_by_name(inp_buf);
    if (cmd.info == nullptr)
        THROW_SYNTAX_ERROR_("Command not found.");
    cmd.byte.num = cmd.info->num & CMD_BYTE_NUM_BIT_MASK;
    line.str = strtok(nullptr, "");
    line.str = str_skip_spaces(line.str);
    STATUS_CHECK(asm_parse_is_arg_ram(&line.str, &cmd, line_num));
    line.str = strtok(line.str, " +");
    if (cmd.info->args.reg)
        STATUS_CHECK(asm_read_reg(line.str, &cmd, line_num));
    if (cmd.info->args.imm) {
        if (cmd.byte.reg) // If reg was given - do strtok
            line.str = strtok(nullptr, " +");
        STATUS_CHECK(asm_read_imm(line.str, &cmd, line_num));
    }
    if ((cmd.info->args.imm || cmd.info->args.reg) &&
        !(cmd.byte.imm || cmd.byte.reg))
            THROW_SYNTAX_ERROR_("At least one argument required.");
    STATUS_CHECK(asm_write_cmd(file, &cmd, &binary_pos, line_num, debug_mode, comment));
    return Status::NORMAL_WORK;
}
References CmdInfo::args, asm_parse_is_arg_ram(), asm_read_imm(), asm_read_reg(), asm_write_cmd(), Cmd::byte, CMD_BYTE_NUM_BIT_MASK, find_command_by_name(), CmdByte::imm, ArgsEn::imm, Cmd::info, MAX_LINE_LEN, Status::NORMAL_WORK, CmdByte::num, CmdInfo::num, CmdByte::reg, ArgsEn::reg, SIGNATURE, STATUS_CHECK, String::str, str_skip_spaces(), text_throw_out_comment(), and THROW_SYNTAX_ERROR_.
Referenced by assemeble_and_write().
asm_parse_is_arg_ram()
Status::Statuses asm_parse_is_arg_ram (char ** str, Cmd * cmd, const size_t line_num)
Checks if [] are specified (ram arguments)
Parameters
str
cmd
line_num
Returns
Status::Statuses
Definition at line 97 of file assembler.cpp.
                                                                                 {
    assert(cmd);
    if (*str == nullptr)
        return Status::NORMAL_WORK;
    if (**str == '[') {
        (*str)++;
        char* end = strchr(*str, ']');
        if (end == nullptr)
            THROW_SYNTAX_ERROR_("Expected \"]\".");
        *end = '\0';
        if (!cmd->info->args.ram)
            THROW_SYNTAX_ERROR_("Command doesn't support ram arg.");
        cmd->byte.ram = true;
    }
    return Status::NORMAL_WORK;
}
References CmdInfo::args, Cmd::byte, Cmd::info, Status::NORMAL_WORK, CmdByte::ram, ArgsEn::ram, and THROW_SYNTAX_ERROR_.
Referenced by asm_parse_and_write_line().
asm_read_imm()
Status::Statuses asm_read_imm (const char * str, Cmd * cmd, const size_t line_num)
Reads cmd imm from str.
Parameters
str
cmd
line_num
Returns
Status::Statuses
Definition at line 153 of file assembler.cpp.
                                                                              {
    assert(cmd);
    if (str == nullptr)
        return Status::NORMAL_WORK;
    if (cmd->byte.ram) {
        int sscanf_res = sscanf(str, IMM_RAM_T_PRINTF, &cmd->args.imm_ram);
        if (sscanf_res != 1)
            THROW_SYNTAX_ERROR_("Invalid immediate argument \"%s\"", str,);
    } else {
        int sscanf_res = sscanf(str, IMM_T_PRINTF, &cmd->args.imm);
        if (sscanf_res != 1)
            THROW_SYNTAX_ERROR_("Invalid immediate argument \"%s\"", str,);
    }
    cmd->byte.imm = true;
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, IMM_RAM_T_PRINTF, IMM_T_PRINTF, Status::NORMAL_WORK, CmdByte::ram, and THROW_SYNTAX_ERROR_.
Referenced by asm_parse_and_write_line().
asm_read_reg()
Status::Statuses asm_read_reg (const char * str, Cmd * cmd, const size_t line_num)
Reads cmd reg from str.
Parameters
str
cmd
line_num
Returns
Status::Statuses
Definition at line 128 of file assembler.cpp.
                                                                              {
    assert(cmd);
    if (str == nullptr)
        return Status::NORMAL_WORK;
    if (isalpha(str[0])) {
        const RegInfo* reg = find_reg_by_name(str);
        if (reg == nullptr)
            THROW_SYNTAX_ERROR_("Invalid reg name \"%s\"", str,);
        cmd->args.reg = reg->num;
        cmd->byte.reg = true;
    }
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, find_reg_by_name(), Status::NORMAL_WORK, CmdByte::reg, CmdArgs::reg, reg, and THROW_SYNTAX_ERROR_.
Referenced by asm_parse_and_write_line().
asm_write_cmd()
Status::Statuses asm_write_cmd (FILE * file, const Cmd * cmd, size_t * binary_pos, const size_t line_num, const bool debug_mode, const char * comment)
Writes command to file.
Parameters
file
cmd
binary_pos
line_num
debug_mode
comment
Returns
Status::Statuses
Definition at line 178 of file assembler.cpp.
                                                                                                  {
    assert(file);
    if (debug_mode)
        STATUS_CHECK(asm_write_cmd_debug(file, cmd, *binary_pos, line_num, comment));
    else
        STATUS_CHECK(asm_write_cmd_bin(file, cmd));
    if (cmd == nullptr)
        return Status::NORMAL_WORK;
    *binary_pos += sizeof(cmd->byte) + cmd->byte.reg * sizeof(cmd->args.reg)
                                     + cmd->byte.imm * (cmd->byte.ram ? sizeof(cmd->args.imm_ram)
                                                                      : sizeof(cmd->args.imm));
    return Status::NORMAL_WORK;
}
References Cmd::args, asm_write_cmd_bin(), asm_write_cmd_debug(), Cmd::byte, CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, Status::NORMAL_WORK, CmdByte::ram, CmdByte::reg, CmdArgs::reg, and STATUS_CHECK.
Referenced by asm_parse_and_write_line().
asm_write_cmd_bin()
Status::Statuses asm_write_cmd_bin (FILE * file, const Cmd * cmd)
Writes cmd in binary mode.
Parameters
file
cmd
Returns
Status::Statuses
Definition at line 269 of file assembler.cpp.
                                                             {
    assert(file);
    if (cmd == nullptr)
        return Status::NORMAL_WORK;
    F_WRITE_CHECK_(file_write_bytes(file, &cmd->byte, sizeof(cmd->byte)));
    if (cmd->byte.reg)
        F_WRITE_CHECK_(file_write_bytes(file, &cmd->args.reg, sizeof(cmd->args.reg)));
    if (cmd->byte.imm) {
        if (cmd->byte.ram) {
            F_WRITE_CHECK_(file_write_bytes(file, &cmd->args.imm_ram, sizeof(cmd->args.imm_ram)));
        } else {
            F_WRITE_CHECK_(file_write_bytes(file, &cmd->args.imm, sizeof(cmd->args.imm)));
        }
    }
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, F_WRITE_CHECK_, file_write_bytes(), CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, Status::NORMAL_WORK, CmdByte::ram, CmdByte::reg, and CmdArgs::reg.
Referenced by asm_write_cmd().
asm_write_cmd_debug()
Status::Statuses asm_write_cmd_debug (FILE * file, const Cmd * cmd, const size_t binary_pos, const size_t line_num, const char * comment)
Writes cmd in text mode.
Parameters
file
cmd
binary_pos
line_num
comment
Returns
Status::Statuses
Definition at line 201 of file assembler.cpp.
                                                          {
    assert(file);
    F_PRINTF_CHECK_(file_printf(file, ";%4zu - %4zu -", line_num, binary_pos));
    if (cmd == nullptr) {
        F_PRINTF_CHECK_(file_printf(file, "%*s -", asm_debug_calc_tab(cmd), ""));
        F_WRITE_CHECK_(asm_write_debug_comment(file, comment));
        F_PRINTF_CHECK_(file_printf(file, "\n"));
        return Status::NORMAL_WORK;
    }
    // Command in hex format
    F_PRINTF_CHECK_(file_printf(file, " %02X", cmd->byte));
    if (cmd->byte.reg)
        for (size_t i = 0; i < sizeof(cmd->args.reg); i++)
            F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->args.reg)[i]));
    if (cmd->byte.imm)
        for (size_t i = 0; i < sizeof(cmd->args.imm); i++)
            F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->args.imm)[i]));
    F_PRINTF_CHECK_(file_printf(file, "%*s", asm_debug_calc_tab(cmd), ""));
    // Command in text format
    F_PRINTF_CHECK_(file_printf(file, " - %s", cmd->info->name));
    if (cmd->byte.ram) {
        F_PRINTF_CHECK_(file_printf(file, " ["));
    } else if (cmd->byte.imm || cmd->byte.reg) {
        F_PRINTF_CHECK_(file_printf(file, " "));
    }
    if (cmd->byte.reg)
        F_PRINTF_CHECK_(file_printf(file, "%s", find_reg_by_num(cmd->args.reg)->name));
    if (cmd->byte.imm) {
        if (cmd->byte.reg)
            F_PRINTF_CHECK_(file_printf(file, "+"));
        if (cmd->byte.ram) {
            F_PRINTF_CHECK_(file_printf(file, IMM_RAM_T_PRINTF, cmd->args.imm_ram));
        } else {
            F_PRINTF_CHECK_(file_printf(file, IMM_T_PRINTF, cmd->args.imm));
        }
    }
    if (cmd->byte.ram)
        F_PRINTF_CHECK_(file_printf(file, "]"));
    F_WRITE_CHECK_(asm_write_debug_comment(file, comment));
    F_PRINTF_CHECK_(file_printf(file, "\n"));
    return Status::NORMAL_WORK;
}
References Cmd::args, asm_debug_calc_tab(), asm_write_debug_comment(), Cmd::byte, F_PRINTF_CHECK_, F_WRITE_CHECK_, file_printf(), find_reg_by_num(), CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, IMM_RAM_T_PRINTF, IMM_T_PRINTF, Cmd::info, RegInfo::name, CmdInfo::name, Status::NORMAL_WORK, CmdByte::ram, CmdByte::reg, and CmdArgs::reg.
Referenced by asm_write_cmd().
asm_write_debug_comment()
bool asm_write_debug_comment (FILE * file, const char * comment)
Writes comment to listing file.
Parameters
file
comment
Returns
true
false
Definition at line 314 of file assembler.cpp.
                                                              {
    if (comment == nullptr)
        return true;
    if (file_printf(file, " ;%s", comment) == EOF)
        return false;
    return true;
}
References file_printf().
Referenced by asm_write_cmd_debug().
asm_write_signature()
Status::Statuses asm_write_signature (FILE * file, const bool debug_mode)
Writes signature to file.
Parameters
file
debug_mode
Returns
Status::Statuses
Definition at line 296 of file assembler.cpp.
                                                                      {
    assert(file);
    if (debug_mode) {
        static_assert(sizeof(SIGNATURE.name) == 2);
        F_PRINTF_CHECK_(file_printf(file, ";Signature: %c%c\n"
                                          ";Version: %d\n",
                                          SIGNATURE.name[0], SIGNATURE.name[1], SIGNATURE.version));
    } else
        F_WRITE_CHECK_(file_write_bytes(file, &SIGNATURE, sizeof(SIGNATURE)));
    return Status::NORMAL_WORK;
}
References F_PRINTF_CHECK_, F_WRITE_CHECK_, file_printf(), file_write_bytes(), Signature::name, Status::NORMAL_WORK, SIGNATURE, and Signature::version.
Referenced by assemeble_and_write().
assemeble_and_write()
Status::Statuses assemeble_and_write (const InputData * input_data, const char * filename, bool debug_mode)
Assembles code and writes it to binary or text file.
Parameters
input_data
filename
debug_mode
Returns
Status::Statuses
Definition at line 3 of file assembler.cpp.
                                                     {
    assert(input_data);
    assert(filename);
    FILE* file = {};
    if (!file_open(&file, filename, "wb"))
        return Status::OUT_FILE_ERROR;
    STATUS_CHECK(asm_write_signature(file, debug_mode), file_close(file));
    if (debug_mode)
        if (file_printf(file, ";line - byte - command\n") == EOF)
            return Status::OUT_FILE_ERROR;
    for (size_t i = 0; i < input_data->lines_cnt; i++) {
        STATUS_CHECK(asm_parse_and_write_line(file, input_data->lines[i], i + 1, debug_mode),
                     file_close(file));
    }
    if (!file_close(file))
        return Status::OUT_FILE_ERROR;
    return Status::NORMAL_WORK;
}
References asm_parse_and_write_line(), asm_write_signature(), file_close(), file_open(), file_printf(), InputData::lines, InputData::lines_cnt, Status::NORMAL_WORK, Status::OUT_FILE_ERROR, and STATUS_CHECK.
Referenced by main().