assembler/src/main.cpp File Reference
#include lib/utils/statuses.h
#include lib/utils/args_parser.h
#include lib/text/text_proccessor.h
#include assembler.h
Functions
int main (int argc, char *argv[])
Variables
const Argument ARGS_DICT []
This array contains console options, their functions and descriptions.
const int ARGS_DICT_LEN = sizeof(ARGS_DICT) / sizeof(ARGS_DICT[0])
Function Documentation
main()
int main (int argc, char * argv[])
Parsing console arguments
Parsing console arguments end
Reading and parsing input file
Reading and parsing input file end
Assembling and writing
Assembling and writing end
Definition at line 22 of file main.cpp.
                                 {
    ArgsVars args_vars = {};
    args_vars.input_filename = "../Programs/example/main.code"; //< default value
    args_vars.output_filename = "../Programs/example/main.exec"; //< default value
    args_vars.listing_filename = "../Programs/example/main.list"; //< default value
    STATUS_CHECK_RAISE(args_parse(argc, argv, &args_vars, ARGS_DICT, ARGS_DICT_LEN));
    InputData input_data = {};
    input_data.ctor(args_vars.input_filename);
    STATUS_CHECK_RAISE(assemeble_and_write(&input_data, args_vars.output_filename,
                                           args_vars.input_filename, args_vars.listing_filename),
                       input_data.detor(););
    input_data.detor();
    return Status::OK_EXIT;
}
References ARGS_DICT, ARGS_DICT_LEN, args_parse(), assemeble_and_write(), InputData::ctor(), InputData::detor(), ArgsVars::input_filename, ArgsVars::listing_filename, Status::OK_EXIT, ArgsVars::output_filename, and STATUS_CHECK_RAISE.
Variable Documentation
ARGS_DICT
const Argument ARGS_DICT[]
Initial value:
= {
    {"-h", print_help, "# -h - prints help information\n"},
    {"-i", read_input_filename, "# -i - specify input file name after this\n"},
    {"-o", read_output_filename, "# -o - specify output file name after this\n"},
    {"-l", read_listing_filename, "# -l - enables and specifies listing file\n"},
}
This array contains console options, their functions and descriptions.
Definition at line 9 of file main.cpp.
Referenced by main().
ARGS_DICT_LEN
const int ARGS_DICT_LEN = sizeof(ARGS_DICT) / sizeof(ARGS_DICT[0])
Definition at line 19 of file main.cpp.
Referenced by main().