shared/cmd.cpp File Reference
#include cmd.h
Functions
const CmdInfo * find_command_by_num (const Cmd_num_t num)
Finds command in CMDS_DICT by num.
const CmdInfo * find_command_by_name (const String name)
Finds command in CMDS_DICT[] by name.
const RegInfo * find_reg_by_num (const RegNum_t num)
Finds reg in REGS_DICT[] by num.
const RegInfo * find_reg_by_name (const String name)
Finds reg in REGS_DICT[] by name.
Function Documentation
find_command_by_name()
const CmdInfo * find_command_by_name (const String name)
Finds command in CMDS_DICT[] by name.
Parameters
name
Returns
const CmdInfo*
Definition at line 36 of file cmd.cpp.
                                                       {
    assert(name.str);
    for (size_t i = 0; i < CMDS_DICT_SIZE; i++)
        if (String_strcasecmp(CMDS_DICT[i].name, String_TO_const(name)) == 0)
            return CMDS_DICT + i;
    return nullptr;
}
References CMDS_DICT, CMDS_DICT_SIZE, String_strcasecmp(), and String_TO_const.
Referenced by asm_read_cmd().
find_command_by_num()
const CmdInfo * find_command_by_num (const Cmd_num_t num)
Finds command in CMDS_DICT by num.
Parameters
num
Returns
const CmdInfo*
Definition at line 28 of file cmd.cpp.
                                                        { // TODO switch. Dispatch table, && у метки
    for (size_t i = 0; i < CMDS_DICT_SIZE; i++)
        if (CMDS_DICT[i].num == num)
            return CMDS_DICT + i;
    return nullptr;
}
References CMDS_DICT, and CMDS_DICT_SIZE.
Referenced by disasm_parse().
find_reg_by_name()
const RegInfo * find_reg_by_name (const String name)
Finds reg in REGS_DICT[] by name.
Parameters
name
Returns
const RegInfo*
Definition at line 54 of file cmd.cpp.
                                                   {
    assert(name.str);
    for (size_t i = 0; i < REGS_NUM; i++)
        if (String_strcmp(REGS_DICT[i].name, String_TO_const(name)) == 0)
            return REGS_DICT + i;
    return nullptr;
}
References REGS_DICT, REGS_NUM, String_strcmp(), and String_TO_const.
Referenced by asm_read_arg_reg().
find_reg_by_num()
const RegInfo * find_reg_by_num (const RegNum_t reg)
Finds reg in REGS_DICT[] by num.
Parameters
reg
Returns
const RegInfo*
Definition at line 46 of file cmd.cpp.
                                                   {
    for (size_t i = 0; i < REGS_NUM; i++)
        if (REGS_DICT[i].num == num)
            return REGS_DICT + i;
    return nullptr;
}
References REGS_DICT, and REGS_NUM.
Referenced by asm_write_cmd_listing(), and disasm_parse().