spu/src/stack/config.h File Reference
#include <math.h>
#include cmd.h
#include stack.h
Macros
#define DEBUG
#define CANARY_PROTECT
Stack debug options.
#define HASH_PROTECT
#define ELEM_T_PRINTF %lf
#define CANARY_T_PRINTF %llX
Typedefs
typedef double Elem_t
typedef unsigned long long Canary_t
Functions
bool is_poison (Elem_t elem)
Variables
const char *const STACK_LOG_FILENAME = stack.log
Macro Definition Documentation
CANARY_PROTECT
#define CANARY_PROTECT
Stack debug options.
Definition at line 12 of file config.h.
CANARY_T_PRINTF
#define CANARY_T_PRINTF %llX
Definition at line 27 of file config.h.
DEBUG
#define DEBUG
Definition at line 9 of file config.h.
ELEM_T_PRINTF
#define ELEM_T_PRINTF %lf
Definition at line 19 of file config.h.
HASH_PROTECT
#define HASH_PROTECT
Definition at line 13 of file config.h.
Typedef Documentation
Canary_t
typedef unsigned long long Canary_t
Definition at line 25 of file config.h.
Elem_t
typedef double Elem_t
Definition at line 17 of file config.h.
Function Documentation
is_poison()
bool is_poison (Elem_t elem) [inline]
Definition at line 21 of file config.h.
                                   { //< Poison checking function
    return isnan(elem);
}
Referenced by stk_dump(), stk_push(), and stk_verify().
Variable Documentation
STACK_LOG_FILENAME
const char* const STACK_LOG_FILENAME = stack.log
Definition at line 15 of file config.h.