disassembler/src/disassembler.h File Reference
#include lib/utils/statuses.h
#include cmd.h
#include lib/utils/console.h
#include lib/file/file.h
Functions
Status::Statuses disasm_parse (const char *data, const size_t size, const char *output_filename, const bool debug_mode)
disassembles data to output file
int disasm_write_signature (FILE *file, const Signature sign)
Writes signature to file.
Function Documentation
disasm_parse()
Status::Statuses disasm_parse (const char * data, const size_t size, const char * output_filename, const bool debug_mode)
disassembles data to output file
Parameters
data
size
output_filename
debug_mode
Returns
Status::Statuses
Definition at line 22 of file disassembler.cpp.
                                                     {
    assert(data);
    assert(output_filename);
    Signature sign = {};
    if (size < sizeof(SIGNATURE) || !(sign = *((const Signature*) data)).check())
        return Status::SIGNATURE_ERROR;
    FILE* file = {};
    if (!file_open(&file, output_filename, "wb"))
        return Status::OUT_FILE_ERROR;
    if (disasm_write_signature(file, sign) == EOF) {
        file_close(file);
        return Status::OUT_FILE_ERROR;
    }
    size_t cur_byte = sizeof(SIGNATURE);
    size_t ip = cur_byte; //< Instruction pointer
    Cmd cmd = {};
    while (cur_byte + sizeof(cmd.byte) <= size) {
        DATA_GET_VAL_(cmd.byte, CmdByte);
        cmd.info = find_command_by_num(cmd.byte.num);
        if (cmd.info == nullptr)
            THROW_SYNTAX_ERROR_("Unknown command number.");
        if (cur_byte + cmd.size() > size)
            THROW_SYNTAX_ERROR_("Arguments not found.");
        size_t printed_cnt = 0;
        F_PRINTF_("%s", cmd.info->name);
        if (cmd.byte.ram)
            F_PRINTF_(" [");
        else if (cmd.byte.imm || cmd.byte.reg)
            F_PRINTF_(" ");
        if (cmd.byte.reg) {
            DATA_GET_VAL_(cmd.args.reg, RegNum_t);
            F_PRINTF_("%s", find_reg_by_num(cmd.args.reg)->name);
        }
        if (cmd.byte.imm) {
            if (cmd.byte.reg)
                F_PRINTF_("+");
            if (cmd.byte.ram) {
                DATA_GET_VAL_(cmd.args.imm_ram, Imm_ram_t);
                F_PRINTF_(IMM_RAM_T_PRINTF, cmd.args.imm_ram);
            } else {
                DATA_GET_VAL_(cmd.args.imm, Imm_t);
                F_PRINTF_(IMM_T_PRINTF, cmd.args.imm);
            }
        }
        if (cmd.byte.ram)
            F_PRINTF_("]");
        if (debug_mode) {
            static const size_t DISASM_COMMENTS_OFFSET = 50;
            if (printed_cnt < DISASM_COMMENTS_OFFSET)
                F_PRINTF_("%*s", DISASM_COMMENTS_OFFSET - printed_cnt, "");
            F_PRINTF_(";byte=%zu", ip);
        }
        F_PRINTF_("\n");
        ip = cur_byte;
    }
    if (!file_close(file))
        return Status::OUT_FILE_ERROR;
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, DATA_GET_VAL_, disasm_write_signature(), F_PRINTF_, file_close(), file_open(), find_command_by_num(), find_reg_by_num(), CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, IMM_RAM_T_PRINTF, IMM_T_PRINTF, Cmd::info, RegInfo::name, CmdInfo::name, Status::NORMAL_WORK, CmdByte::num, Status::OUT_FILE_ERROR, CmdByte::ram, CmdByte::reg, CmdArgs::reg, SIGNATURE, Status::SIGNATURE_ERROR, Cmd::size(), and THROW_SYNTAX_ERROR_.
Referenced by main().
disasm_write_signature()
int disasm_write_signature (FILE * file, const Signature sign)
Writes signature to file.
Parameters
file
sign
Returns
int
Definition at line 116 of file disassembler.cpp.
                                                             {
    assert(file);
    static_assert(sizeof(sign.name) == 2);
    F_PRINTF_CHECK_(file_printf(file, ";Signature: %c%c\n"
                                      ";Version: %d\n",
                                      sign.name[0], sign.name[1], sign.version));
    return 1;
}
References F_PRINTF_CHECK_, file_printf(), Signature::name, and Signature::version.
Referenced by disasm_parse().