disassembler/src/main.cpp File Reference
#include "lib/utils/statuses.h"
#include "lib/utils/args_parser.h"
#include "lib/file/file.h"
#include "lib/utils/macros.h"
#include "disassembler.h"
Functions
int main (int argc, char *argv[])
Variables
const Argument ARGS_DICT []
This array contains console options, their functions and descriptions.
const int ARGS_DICT_LEN = sizeof(ARGS_DICT) / sizeof(ARGS_DICT[0])
args_dict array len
Function Documentation
main()
int main (int argc, char * argv[])
Parsing console arguments
Parsing console arguments end
Reading input data
Reading input data end
Parsing and writing commands
Parsing and writing command end
Definition at line 24 of file main.cpp.
                                 {
    ArgsVars args_vars = {};
    args_vars.input_filename = "../Programs/example/main.exec"; //< default value
    args_vars.output_filename = "../Programs/example/main.disasm"; //< default value
    args_vars.debug_mode = false; //< default value
    STATUS_CHECK_RAISE(args_parse(argc, argv, &args_vars, ARGS_DICT, ARGS_DICT_LEN));
    char* inp_data = nullptr;
    long size = 0;
    STATUS_CHECK_RAISE(file_open_read_close(args_vars.input_filename, &inp_data, 0, &size),
                       FREE(inp_data));
    STATUS_CHECK_RAISE(disasm_parse(inp_data, size, args_vars.output_filename, args_vars.debug_mode),
                       FREE(inp_data));
    FREE(inp_data);
    return Status::OK_EXIT;
}
References ARGS_DICT, ARGS_DICT_LEN, args_parse(), ArgsVars::debug_mode, disasm_parse(), file_open_read_close(), FREE, ArgsVars::input_filename, Status::OK_EXIT, ArgsVars::output_filename, and STATUS_CHECK_RAISE.
Variable Documentation
ARGS_DICT
const Argument ARGS_DICT[]
Initial value:
= {
    {"-h", print_help, "# -h - prints help information\n"},
    {"-i", read_input_filename, "# -i - specify input file name after this\n"},
    {"-o", read_output_filename, "# -o - specify output file name after this\n"},
    {"-d", enable_debug_mode, "# -d - enables debug mode "
                                 "(writes byte posiotion of every command)\n"},
}
This array contains console options, their functions and descriptions.
Definition at line 10 of file main.cpp.
                             {
    {"-h", print_help, "# -h - prints help information\n"},
    {"-i", read_input_filename, "# -i - specify input file name after this\n"},
    {"-o", read_output_filename, "# -o - specify output file name after this\n"},
    {"-d", enable_debug_mode, "# -d - enables debug mode "
                                 "(writes byte posiotion of every command)\n"},
};
ARGS_DICT_LEN
const int ARGS_DICT_LEN = sizeof(ARGS_DICT) / sizeof(ARGS_DICT[0])
args_dict array len
Definition at line 21 of file main.cpp.