assembler/src/asm/errors.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <stdarg.h>
#include "lib/utils/statuses.h"
#include "lib/text/text_lib.h"
#include "lib/utils/console.h"
#include "cmd.h"
#include "asm.h"
Functions
Status::Statuses asm_throw_syntax_error (const Asm *asm_data, const AsmLine *line, const char *err_msg,...)
Throws syntax error.
bool cmd_is_arg_required (const Cmd *cmd)
Checks if cmd requires at least one argument.
bool cmd_is_any_arg_given (const Cmd *cmd)
Checks if at least one argument was given to a function.
Function Documentation
asm_throw_syntax_error()
Status::Statuses asm_throw_syntax_error (const Asm * asm_data, const AsmLine * line, const char * err_msg, ...)
Throws syntax error.
Parameters
asm_data
line
err_msg
...
Returns
Status::Statuses always SYNTAX_ERROR
Definition at line 3 of file errors.cpp.
                                                                  {
    assert(asm_data);
    assert(line);
    assert(err_msg);
    const String err_token = line->tokens[line->cur_token];
    const int token_begin = (err_token.str == nullptr) ? (int)line->text.len
                                                       : (int)(err_token.str - line->text.str);
    const int token_end = (err_token.str == nullptr) ? (int)line->text.len
                                                       : (int)(token_begin + err_token.len);
    fprintf(stderr, CONSOLE_STYLE(STYLE_BOLD, "%s:%zu:%d "
                                  COLOR_RED "syntax error: "),
                    asm_data->files.inp_name, line->num, token_begin + 1);
    va_list arg_list = {};
    va_start(arg_list, err_msg);
    vfprintf(stderr, err_msg, arg_list);
    va_end(arg_list);
    fprintf(stderr, "\n");
    fprintf(stderr, "%5zu | ", line->num);
    fprintf(stderr, "%.*s", token_begin, line->text.str);
    fprintf(stderr, CONSOLE_STYLE(STYLE_BOLD COLOR_RED, "%.*s"), String_PRINTF(err_token));
    fprintf(stderr, "%.*s\n", (int)(line->text.len - token_end), line->text.str + token_end);
    fprintf(stderr, "%5s | ", "");
    fprintf(stderr, "%*s", token_begin, "");
    fprintf(stderr, COLOR_RED STYLE_BOLD "^");
    for (ssize_t i = 0; i < token_end - token_begin - 1; i++)
        fprintf(stderr, "~");
    fprintf(stderr, STYLE_RESET "\n");
    return Status::SYNTAX_ERROR;
}
References COLOR_RED, CONSOLE_STYLE, AsmLine::cur_token, Asm::files, AsmFilesInfo::inp_name, String::len, AsmLine::num, String::str, String_PRINTF, STYLE_BOLD, STYLE_RESET, Status::SYNTAX_ERROR, AsmLine::text, and AsmLine::tokens.
cmd_is_any_arg_given()
bool cmd_is_any_arg_given (const Cmd * cmd) [inline]
Checks if at least one argument was given to a function.
Parameters
cmd
Returns
true
false
Definition at line 66 of file errors.h.
                                                 {
    return cmd->keys.imm_int || cmd->keys.imm_double || cmd->keys.reg; //< ram check is not needed
}
References CmdKeys::imm_double, CmdKeys::imm_int, Cmd::keys, and CmdKeys::reg.
Referenced by asm_parse_and_write_line(), and asm_write_cmd_listing().
cmd_is_arg_required()
bool cmd_is_arg_required (const Cmd * cmd) [inline]
Checks if cmd requires at least one argument.
Parameters
cmd
Returns
true
false
Definition at line 49 of file errors.h.
                                                {
    assert(cmd);
    if (cmd->info == nullptr)
        return false;
    return cmd->info->is_args.label || cmd->info->is_args.imm_int || cmd->info->is_args.imm_double
        || cmd->info->is_args.reg; //< ram check is not needed
}
References ArgsEnabled::imm_double, ArgsEnabled::imm_int, Cmd::info, CmdInfo::is_args, ArgsEnabled::label, and ArgsEnabled::reg.
Referenced by asm_parse_and_write_line().