shared/lib/file/file.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>
#include ../utils/statuses.h
Functions
Status::Statuses file_open_read_close (const char *filename, char **buf, const size_t additional_memory=0, long *size=nullptr)
Opens, reads and closes file. Allocates memory.
Status::Statuses file_open_write_bytes_close (const char *filename, char *buf, const size_t size)
Opens, writes bytes and closes file.
bool file_open (FILE **file, const char *filename, const char *mode)
Opens file.
long file_get_len (FILE *file)
Gets file len.
bool file_read (FILE *file, char *buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
bool file_write_line (FILE *file, const char *line)
Writes line (string) to file.
bool file_write_bytes (FILE *file, const void *data, size_t len)
Writes data to file.
int file_printf (FILE *file, const char *format,...)
Error handler for fprintf.
bool file_close (FILE *file)
Closes file.
Function Documentation
file_close()
bool file_close (FILE * file)
Closes file.
Parameters
file
Returns
true success
false failure
Definition at line 141 of file file.cpp.
                            {
    assert(file);
    if (fclose(file) != 0) {
        perror("File close error");
        return false;
    }
    return true;
}
Referenced by assemeble_and_write(), disasm_parse(), file_open_read_close(), and file_open_write_bytes_close().
file_get_len()
long file_get_len (FILE * file)
Gets file len.
Parameters
file
Returns
long -1 in case of error
Definition at line 70 of file file.cpp.
                              {
    assert(file);
    long file_len = -1;
    if (fseek(file, 0, SEEK_END) != 0 ||
        (file_len = ftell(file)) == -1L ||
        fseek(file, 0, SEEK_SET) != 0) {
            perror("File len detection error");
            return -1;
    }
    return file_len;
}
Referenced by file_open_read_close().
file_open()
bool file_open (FILE ** file, const char * filename, const char * mode)
Opens file.
Parameters
file
filename
mode
Returns
true success
false failure
Definition at line 56 of file file.cpp.
                                                                    {
    assert(file);
    assert(filename);
    assert(mode);
    *file = fopen(filename, mode);
    if (*file == nullptr) {
        fprintf(stderr, "Error opening file %s:\n", filename);
        perror("");
        return false;
    }
    return true;
}
Referenced by assemeble_and_write(), disasm_parse(), file_open_read_close(), and file_open_write_bytes_close().
file_open_read_close()
Status::Statuses file_open_read_close (const char * filename, char ** buf, const size_t additional_memory = 0, long * size = nullptr)
Opens, reads and closes file. Allocates memory.
Parameters
filename
buf
additional_memory will be allocated in addition to the file size
size readed file size
Returns
Status::Statuses
Definition at line 3 of file file.cpp.
                                                  {
    assert(filename);
    assert(buf);
    assert(*buf == nullptr);
    long file_size = 0;
    FILE* file = nullptr;
    if (!file_open(&file, filename, "rb"))
        return Status::INP_FILE_ERROR;
    file_size = file_get_len(file);
    if (file_size < 0)
        return Status::INP_FILE_ERROR;
    if (size != nullptr)
        *size = file_size;
    *buf = (char*)calloc(file_size + additional_memory, sizeof(char));
    if (*buf == nullptr) {
        fprintf(stderr, "Memory alloc error\n");
        file_close(file);
        return Status::MEMORY_EXCEED;
    }
    if (!file_read(file, *buf, file_size))
        return Status::INP_FILE_ERROR;
    if (!file_close(file))
        return Status::INP_FILE_ERROR;
    return Status::NORMAL_WORK;
}
References file_close(), file_get_len(), file_open(), file_read(), Status::INP_FILE_ERROR, Status::MEMORY_EXCEED, and Status::NORMAL_WORK.
Referenced by InputData::ctor(), and main().
file_open_write_bytes_close()
Status::Statuses file_open_write_bytes_close (const char * filename, char * buf, const size_t size)
Opens, writes bytes and closes file.
Parameters
filename
buf
size
Returns
Status::Statuses
Definition at line 38 of file file.cpp.
                                                                                               {
    assert(filename);
    assert(buf);
    FILE* file = nullptr;
    if (!file_open(&file, filename, "wb"))
        return Status::OUT_FILE_ERROR;
    if (!file_write_bytes(file, buf, size))
        return Status::OUT_FILE_ERROR;
    if (!file_close(file))
        return Status::OUT_FILE_ERROR;
    return Status::NORMAL_WORK;
}
References file_close(), file_open(), file_write_bytes(), Status::NORMAL_WORK, and Status::OUT_FILE_ERROR.
Referenced by assemeble_and_write().
file_printf()
int file_printf (FILE * file, const char * format, ...)
Error handler for fprintf.
Parameters
file
format
...
Returns
int number of printed symbols or EOF
Definition at line 124 of file file.cpp.
                                                    {
    assert(file);
    assert(format);
    va_list args = {};
    va_start(args, format);
    int res = vfprintf(file, format, args);
    va_end(args);
    if (res == EOF)
        perror("File write error");
    return res;
}
Referenced by asm_write_cmd_listing(), asm_write_header_listing(), asm_write_listing_comment(), assemeble_and_write(), and disasm_write_header().
file_read()
bool file_read (FILE * file, char * buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
Parameters
file
buf
file_len
Returns
true
false
Definition at line 86 of file file.cpp.
                                                     {
    assert(file);
    assert(buf);
    size_t readed = fread(buf, sizeof(char), file_len, file);
    if (readed != (size_t)file_len || ferror(file)) {
        perror("File read error");
        return false;
    }
    return true;
}
Referenced by file_open_read_close().
file_write_bytes()
bool file_write_bytes (FILE * file, const void * data, size_t len)
Writes data to file.
Parameters
file
data
len data size in bytes
Returns
true
false
Definition at line 112 of file file.cpp.
                                                                {
    assert(file);
    assert(data);
    if (fwrite(data, 1, len, file) != len) {
        perror("File write error");
        return false;
    }
    return true;
}
Referenced by file_open_write_bytes_close().
file_write_line()
bool file_write_line (FILE * file, const char * line)
Writes line (string) to file.
Parameters
file
line
Returns
true
false
Definition at line 100 of file file.cpp.
                                                   {
    assert(file);
    assert(line);
    if (fputs(line, file) == EOF) {
        perror("File write error");
        return false;
    }
    return true;
}