assembler/src/asm/jump.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include "lib/utils/statuses.h"
#include "cmd.h"
#include "errors.h"
#include "asm.h"
Functions
Status::Statuses asm_new_label (const String name, const size_t addr, Asm *asm_data, const AsmLine *line)
Adds new label to labels.
Status::Statuses asm_get_label_addr (const String name, const Asm *asm_data, const AsmLine *line, Imm_int_t *addr)
Gets label addr by name.
const_String asm_get_label_name (const JumpLabel *lables, const Imm_int_t addr)
Returns label name by addr.
Function Documentation
asm_get_label_addr()
Status::Statuses asm_get_label_addr (const String name, const Asm * asm_data, const AsmLine * line, Imm_int_t * addr)
Gets label addr by name.
Parameters
name
asm_data
line
addr
Returns
Status::Statuses
Definition at line 27 of file jump.cpp.
                                                                          {
    assert(name.str);
    assert(asm_data);
    assert(line);
    assert(addr);
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (String_strcmp(String_TO_const(asm_data->labels[i].name), String_TO_const(name)) == 0) {
            *addr = asm_data->labels[i].addr;
            return Status::NORMAL_WORK;
        }
    }
    if (asm_data->pass_num == asm_data->LAST_PASS_NUM)
        THROW_SYNTAX_ERROR_("Unknown label \"%.*s\"", String_PRINTF(name));
    return Status::NORMAL_WORK;
}
References JumpLabel::addr, Asm::labels, Asm::LAST_PASS_NUM, MAX_LABEL_NUM, JumpLabel::name, Status::NORMAL_WORK, Asm::pass_num, String_PRINTF, String_strcmp(), String_TO_const, and THROW_SYNTAX_ERROR_.
Referenced by asm_read_arg_label().
asm_get_label_name()
const_String asm_get_label_name (const JumpLabel * lables, const Imm_int_t addr)
Returns label name by addr.
Parameters
lables
addr
Returns
const_String
Definition at line 48 of file jump.cpp.
                                                                               {
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (labels[i].addr == addr)
            return {labels[i].name.str, labels[i].name.len};
    }
    return String_CONST("!Label name not found!");
}
References MAX_LABEL_NUM, and String_CONST.
Referenced by asm_write_cmd_listing().
asm_new_label()
Status::Statuses asm_new_label (const String name, const size_t addr, Asm * asm_data, const AsmLine * line)
Adds new label to labels.
Parameters
name
addr
asm_data
line
Returns
Status::Statuses
Definition at line 5 of file jump.cpp.
                                                                   {
    assert(name.str);
    assert(asm_data);
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (String_strcmp(String_TO_const(asm_data->labels[i].name), String_TO_const(name)) == 0)
            THROW_SYNTAX_ERROR_("Label name \"%.*s\" used twice.", String_PRINTF(name));
    }
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (asm_data->labels[i].name.len == 0 && asm_data->labels[i].addr == -1) {
            asm_data->labels[i].name = name;
            asm_data->labels[i].addr = addr;
            return Status::NORMAL_WORK;
        }
    }
    THROW_SYNTAX_ERROR_("Too many labels specified. Max %zu.", MAX_LABEL_NUM);
}
References JumpLabel::addr, Asm::labels, String::len, MAX_LABEL_NUM, JumpLabel::name, Status::NORMAL_WORK, String_PRINTF, String_strcmp(), String_TO_const, and THROW_SYNTAX_ERROR_.
Referenced by asm_read_cmd().