assembler/src/asm/jump.cpp File Reference
#include jump.h
Macros
#define THROW_SYNTAX_ERROR_(...)
Functions
Status::Statuses asm_new_label (JumpLabel *labels, const String name, const AsmInfo *inp_file, const size_t byte)
Adds new label to labels.
Status::Statuses asm_get_label_byte (JumpLabel *labels, const String name, const AsmInfo *inp_file, Imm_int_t *byte, const bool final_pass)
Gets label byte by name.
c_String asm_get_label_name (const JumpLabel *labels, const Imm_int_t byte)
Returns label name by byte.
Macro Definition Documentation
THROW_SYNTAX_ERROR_
#define THROW_SYNTAX_ERROR_(...)
Value:
                                                                return asm_throw_syntax_error(name, \
                                                                inp_file, \
                                                                __VA_ARGS__)
Definition at line 3 of file jump.cpp.
Function Documentation
asm_get_label_byte()
Status::Statuses asm_get_label_byte (JumpLabel * labels, const String name, const AsmInfo * inp_file, Imm_int_t * byte, const bool final_pass)
Gets label byte by name.
Parameters
labels
name
inp_file
byte
final_pass
Returns
Status::Statuses
Definition at line 29 of file jump.cpp.
                                                           {
    assert(labels);
    assert(name.str);
    assert(inp_file);
    assert(byte);
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (String_strcmp(String_TO_c(labels[i].name), String_TO_c(name)) == 0) {
            *byte = labels[i].byte;
            return Status::NORMAL_WORK;
        }
    }
    if (final_pass)
        THROW_SYNTAX_ERROR_("Unknown label \"%.*s\"", String_PRINTF(name));
    return Status::NORMAL_WORK;
}
References JumpLabel::byte, MAX_LABEL_NUM, Status::NORMAL_WORK, String::str, String_PRINTF, String_strcmp(), String_TO_c, and THROW_SYNTAX_ERROR_.
Referenced by asm_read_arg_label().
asm_get_label_name()
c_String asm_get_label_name (const JumpLabel * lables, const Imm_int_t byte)
Returns label name by byte.
Parameters
lables
byte
Returns
c_String
Definition at line 51 of file jump.cpp.
                                                                           {
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (labels[i].byte == byte)
            return {labels[i].name.str, labels[i].name.len};
    }
    return String_CONST("!Label name not found!");
}
References String::len, MAX_LABEL_NUM, JumpLabel::name, String::str, and String_CONST.
Referenced by asm_write_cmd_listing().
asm_new_label()
Status::Statuses asm_new_label (JumpLabel * labels, const String name, const AsmInfo * inp_file, const size_t byte)
Adds new label to labels.
Parameters
labels
name
inp_file
byte
Returns
Status::Statuses
Definition at line 7 of file jump.cpp.
                                                                           {
    assert(labels);
    assert(name.str);
    assert(inp_file);
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (String_strcmp(String_TO_c(labels[i].name), String_TO_c(name)) == 0)
            THROW_SYNTAX_ERROR_("Label name \"%.*s\" used twice.", String_PRINTF(name));
    }
    for (size_t i = 0; i < MAX_LABEL_NUM; i++) {
        if (labels[i].name.str == nullptr && labels[i].name.len == 0 && labels[i].byte == -1) {
            labels[i].name = name;
            labels[i].byte = byte;
            return Status::NORMAL_WORK;
        }
    }
    THROW_SYNTAX_ERROR_("Too many labels specified. Max %zu.", MAX_LABEL_NUM);
}
References JumpLabel::byte, String::len, MAX_LABEL_NUM, JumpLabel::name, Status::NORMAL_WORK, String::str, String_PRINTF, String_strcmp(), String_TO_c, and THROW_SYNTAX_ERROR_.
Referenced by asm_parse_and_write_line().