assembler/src/asm/listing.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include "lib/utils/statuses.h"
#include "cmd.h"
#include "lib/utils/macros.h"
#include "lib/file/file.h"
#include "jump.h"
#include "errors.h"
Functions
Status::Statuses asm_write_cmd_listing (FILE *file, const Asm *asm_data, const AsmLine *line)
Writes command to listing.
bool asm_write_listing_comment (FILE *file, const char *comment)
Writes comment to listing file.
Status::Statuses asm_write_header_listing (FILE *listing_file)
Writes header to listing.
int cmd_listing_calc_tab (const Cmd *cmd)
Calculates tab for listing.
Function Documentation
asm_write_cmd_listing()
Status::Statuses asm_write_cmd_listing (FILE * file, const Asm * asm_data, const AsmLine * line)
Writes command to listing.
Parameters
file
asm_data
line
Returns
Status::Statuses
Definition at line 6 of file listing.cpp.
                                                                                           {
    assert(file);
    assert(asm_data);
    assert(line);
    F_PRINTF_CHECK_(file_printf(file, ";%4zu | %04zu |", line->num, asm_data->buf.size));
    if (line->cmd.info == nullptr) {
        F_PRINTF_CHECK_(file_printf(file, "%*s | ", cmd_listing_calc_tab(&line->cmd), ""));
        const_String text = String_skip_spaces(String_TO_const(line->text));
        if (text.len != 0)
            F_WRITE_CHECK_(file_printf(file, "%.*s", String_PRINTF(text)));
        F_PRINTF_CHECK_(file_printf(file, "\n"));
        return Status::NORMAL_WORK;
    }
    // Command in hex format
    const Cmd* cmd = &line->cmd;
    for (size_t i = 0; i < sizeof(cmd->keys); i++)
        F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->keys)[i]));
    if (cmd->keys.reg)
        for (size_t i = 0; i < sizeof(cmd->args.reg); i++)
            F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->args.reg)[i]));
    if (cmd->keys.imm_int)
        for (size_t i = 0; i < sizeof(cmd->args.imm_int); i++)
            F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->args.imm_int)[i]));
    if (cmd->keys.imm_double)
        for (size_t i = 0; i < sizeof(cmd->args.imm_double); i++)
            F_PRINTF_CHECK_(file_printf(file, " %02hhX", ((const char*)&cmd->args.imm_double)[i]));
    F_PRINTF_CHECK_(file_printf(file, "%*s", cmd_listing_calc_tab(cmd), ""));
    // Command in text format
    F_PRINTF_CHECK_(file_printf(file, " | %.*s", String_PRINTF(cmd->info->name)));
    if (cmd->keys.ram) {
        F_PRINTF_CHECK_(file_printf(file, " ["));
    } else if (cmd_is_any_arg_given(cmd)) {
        F_PRINTF_CHECK_(file_printf(file, " "));
    }
    if (cmd->keys.reg) {
        const_String reg_name = find_reg_by_num(cmd->args.reg)->name;
        F_PRINTF_CHECK_(file_printf(file, "%.*s", String_PRINTF(reg_name)));
        if (cmd->keys.imm_int || cmd->keys.imm_double)
            F_PRINTF_CHECK_(file_printf(file, "+"));
    }
    if (cmd->keys.imm_double) {
        F_PRINTF_CHECK_(file_printf(file, IMM_DOUBLE_T_PRINTF, cmd->args.imm_double));
        if (cmd->keys.imm_int)
            F_PRINTF_CHECK_(file_printf(file, "+"));
    }
    if (cmd->keys.imm_int) {
        if (cmd->info->is_args.label && !cmd->keys.ram) {
            const_String label_name = asm_get_label_name(asm_data->labels, cmd->args.imm_int);
            F_PRINTF_CHECK_(file_printf(file, "%.*s (" IMM_INT_T_PRINTF ")",
                                String_PRINTF(label_name), cmd->args.imm_int));
        } else
            F_PRINTF_CHECK_(file_printf(file, IMM_INT_T_PRINTF, cmd->args.imm_int));
    }
    if (cmd->keys.ram)
        F_PRINTF_CHECK_(file_printf(file, "]"));
    F_WRITE_CHECK_(asm_write_listing_comment(file, line->comment));
    F_PRINTF_CHECK_(file_printf(file, "\n"));
    return Status::NORMAL_WORK;
}
References Cmd::args, asm_get_label_name(), asm_write_listing_comment(), Asm::buf, AsmLine::cmd, cmd_is_any_arg_given(), cmd_listing_calc_tab(), AsmLine::comment, F_PRINTF_CHECK_, F_WRITE_CHECK_, file_printf(), find_reg_by_num(), CmdKeys::imm_double, CmdArgs::imm_double, IMM_DOUBLE_T_PRINTF, CmdKeys::imm_int, CmdArgs::imm_int, IMM_INT_T_PRINTF, Cmd::info, CmdInfo::is_args, Cmd::keys, ArgsEnabled::label, Asm::labels, RegInfo::name, CmdInfo::name, Status::NORMAL_WORK, AsmLine::num, CmdKeys::ram, CmdKeys::reg, CmdArgs::reg, Buffer::size, String_PRINTF, String_skip_spaces(), String_TO_const, and AsmLine::text.
Referenced by asm_write_cmd().
asm_write_header_listing()
Status::Statuses asm_write_header_listing (FILE * listing_file)
Writes header to listing.
Parameters
listing_file
Returns
Status::Statuses
Definition at line 90 of file listing.cpp.
                                                            {
    assert(listing_file);
    static_assert(sizeof(FILE_HEADER.sign) == 2);
    F_PRINTF_CHECK_(file_printf(listing_file, ";Signature: %c%c\n"
                                              ";Version: %d\n",
                                FILE_HEADER.sign, FILE_HEADER.sign >> 8, FILE_HEADER.version));
    return Status::NORMAL_WORK;
}
References F_PRINTF_CHECK_, FILE_HEADER, file_printf(), Status::NORMAL_WORK, FileHeader::sign, and FileHeader::version.
Referenced by asm_write_header().
asm_write_listing_comment()
bool asm_write_listing_comment (FILE * file, const char * comment)
Writes comment to listing file.
Parameters
file
comment
Returns
true
false
Definition at line 105 of file listing.cpp.
                                                                {
    if (comment == nullptr)
        return true;
    if (file_printf(file, " %s", comment) == EOF)
        return false;
    return true;
}
References file_printf().
Referenced by asm_write_cmd_listing().
cmd_listing_calc_tab()
int cmd_listing_calc_tab (const Cmd * cmd) [inline]
Calculates tab for listing.
Parameters
cmd
Returns
int
Definition at line 48 of file listing.h.
                                                {
    int res = 0;
    if (cmd->info == nullptr)
        res += sizeof(cmd->keys) * 3;
    if (cmd->info == nullptr || !cmd->keys.reg)
        res += sizeof(cmd->args.reg) * 3;
    if (cmd->info == nullptr || !cmd->keys.imm_int)
        res += sizeof(cmd->args.imm_int) * 3;
    if (cmd->info == nullptr || !cmd->keys.imm_double)
        res += sizeof(cmd->args.imm_double) * 3;
    return res;
}
References Cmd::args, CmdKeys::imm_double, CmdArgs::imm_double, CmdKeys::imm_int, CmdArgs::imm_int, Cmd::info, Cmd::keys, CmdKeys::reg, and CmdArgs::reg.
Referenced by asm_write_cmd_listing().