brasenham_circle Namespace Reference
Functions
set_color (x, y)
draw_circle (x0, y0, R)
Variables
int SCREEN_HEIGHT = 200
int SCREEN_WIDTH = 200
str out = ""
file = open(sys.argv[1], "w")
Function Documentation
draw_circle()
brasenham_circle.draw_circle (x0, y0, R)
Definition at line 18 of file brasenham_circle.py.
def draw_circle(x0, y0, R):
    x = 0
    y = R
    R2 = R**2
    while x >= 0 and y >= 0:
        set_color(x + x0, y + y0)
        set_color(-x + x0, -y + y0)
        set_color(x + x0, -y + y0)
        set_color(-x + x0, y + y0)
        r2 = (x + 1)**2 + (y - 1)**2 - R2
        if r2 < 0:
            d2 = 2*(r2 + y) - 1
            x += 1
            if d2 > 0:
                y -= 1
        elif r2 > 0:
            d2 = 2*(r2 - x) - 1
            y -= 1
            if d2 <= 0:
                x += 1
        else:
            x += 1
            y -= 1
References draw_circle(), and set_color().
Referenced by draw_circle().
set_color()
brasenham_circle.set_color (x, y)
Definition at line 8 of file brasenham_circle.py.
def set_color(x, y):
    global out
    if y < 0 or y >= SCREEN_HEIGHT or x < 0 or x >= SCREEN_WIDTH:
        return
    out += "push 255\n"
    out += "pop [" + str(SCREEN_WIDTH * y + x) + "]\n"
Referenced by draw_circle().
Variable Documentation
file
brasenham_circle.file = open(sys.argv[1], "w")
Definition at line 50 of file brasenham_circle.py.
out
str brasenham_circle.out = ""
Definition at line 6 of file brasenham_circle.py.
SCREEN_HEIGHT
int brasenham_circle.SCREEN_HEIGHT = 200
Definition at line 3 of file brasenham_circle.py.
SCREEN_WIDTH
int brasenham_circle.SCREEN_WIDTH = 200
Definition at line 4 of file brasenham_circle.py.