brasenham_line Namespace Reference
Functions
set_color (x, y)
draw_line (x0, y0, x1, y1)
Variables
int SCREEN_HEIGHT = 200
int SCREEN_WIDTH = 200
str out = ""
file = open(sys.argv[1], "w")
Function Documentation
draw_line()
brasenham_line.draw_line (x0, y0, x1, y1)
Definition at line 18 of file brasenham_line.py.
def draw_line(x0, y0, x1, y1):
    #steep
    steep = False
    if abs(x0 - x1) < abs(y0 - y1):
        x0, y0 = y0, x0
        x1, y1 = y1, x1
        steep = True
    #x0 to the left
    if x0 > x1:
        x0, x1 = x1, x0
        y0, y1 = y1, y0
    """
    var: x0 -> x
    var: y0 -> y
    const: x1 -> x1 (used in "for" condition)
    const: y1 -> y_incr
    const: steep
    const: dx
    var: error2dx
    const: derror2dy
    """
    dx = x1 - x0
    error2dx = 0
    derror2dy = 2 * abs(y1 - y0)
    y = y0
    y_incr = (y0 < y1) if 1 else -1
    for x in range(x0, x1 + 1):
        if steep:
            set_color(y, x)
        else:
            set_color(x, y)
        error2dx += derror2dy
        if error2dx > dx:
            error2dx -= 2*dx
            y += y_incr
References draw_line(), and set_color().
Referenced by draw_line().
set_color()
brasenham_line.set_color (x, y)
Definition at line 8 of file brasenham_line.py.
def set_color(x, y):
    global out
    if y < 0 or y >= SCREEN_HEIGHT or x < 0 or x >= SCREEN_WIDTH:
        return
    out += "push 255\n"
    out += "pop [" + str(SCREEN_WIDTH * y + x) + "]\n"
Referenced by draw_line().
Variable Documentation
file
brasenham_line.file = open(sys.argv[1], "w")
Definition at line 72 of file brasenham_line.py.
out
str brasenham_line.out = ""
Definition at line 6 of file brasenham_line.py.
SCREEN_HEIGHT
int brasenham_line.SCREEN_HEIGHT = 200
Definition at line 3 of file brasenham_line.py.
SCREEN_WIDTH
int brasenham_line.SCREEN_WIDTH = 200
Definition at line 4 of file brasenham_line.py.