assembler/src/asm/read.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <ctype.h>
#include "lib/utils/statuses.h"
#include "lib/text/text_lib.h"
#include "cmd.h"
#include "jump.h"
#include "asm.h"
Functions
Status::Statuses asm_read_cmd (Asm *asm_data, AsmLine *line)
Reads command.
Status::Statuses asm_read_args (const Asm *asm_data, AsmLine *line)
Reads command args.
Status::Statuses asm_read_args_ram (const Asm *asm_data, AsmLine *line)
Reads ram arguments.
Status::Statuses asm_read_arg_reg (const Asm *asm_data, AsmLine *line)
Reads reg argument.
Status::Statuses asm_read_arg_label (const Asm *asm_data, AsmLine *line)
Reads label.
Status::Statuses asm_read_arg_imm_int (const Asm *asm_data, AsmLine *line)
Reads integer immutable argument.
Status::Statuses asm_read_arg_imm_double (const Asm *asm_data, AsmLine *line)
Reads double immutable argument.
Function Documentation
asm_read_arg_imm_double()
Status::Statuses asm_read_arg_imm_double (const Asm * asm_data, AsmLine * line)
Reads double immutable argument.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 143 of file read.cpp.
                                                                           {
    assert(asm_data);
    assert(line);
    String* tokens = line->tokens;
    size_t* cur_token = &line->cur_token;
    if (tokens[*cur_token].len == 0 || !line->cmd.info || !line->cmd.info->is_args.imm_double ||
        line->cmd.keys.imm_double || !maybedigit(tokens[*cur_token].str[0]))
            return Status::NORMAL_WORK;
    int sscanf_num = 0;
    int sscanf_res = String_sscanf(tokens[*cur_token], IMM_DOUBLE_T_PRINTF "%n",
                                   &line->cmd.args.imm_double, &sscanf_num);
    if (sscanf_res != 1 || sscanf_num != tokens[*cur_token].len)
        THROW_SYNTAX_ERROR_("Invalid immediate argument \"%.*s\"",
                                String_PRINTF(tokens[*cur_token]));
    line->cmd.keys.imm_double = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References Cmd::args, AsmLine::cmd, AsmLine::cur_token, CmdKeys::imm_double, CmdArgs::imm_double, ArgsEnabled::imm_double, IMM_DOUBLE_T_PRINTF, Cmd::info, CmdInfo::is_args, Cmd::keys, maybedigit(), Status::NORMAL_WORK, String_PRINTF, String_sscanf(), THROW_SYNTAX_ERROR_, and AsmLine::tokens.
Referenced by asm_read_args().
asm_read_arg_imm_int()
Status::Statuses asm_read_arg_imm_int (const Asm * asm_data, AsmLine * line)
Reads integer immutable argument.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 118 of file read.cpp.
                                                                        {
    assert(asm_data);
    assert(line);
    String* tokens = line->tokens;
    size_t* cur_token = &line->cur_token;
    if (tokens[*cur_token].len == 0 || !line->cmd.info || !line->cmd.info->is_args.ram ||
        line->cmd.keys.imm_int || !maybedigit(tokens[*cur_token].str[0]))
            return Status::NORMAL_WORK;
    int sscanf_num = 0;
    int sscanf_res = String_sscanf(tokens[*cur_token], IMM_INT_T_PRINTF "%n",
                                   &line->cmd.args.imm_int, &sscanf_num);
    if (sscanf_res != 1 || sscanf_num != tokens[*cur_token].len)
        THROW_SYNTAX_ERROR_("Invalid immediate argument \"%.*s\"",
                                String_PRINTF(tokens[*cur_token]));
    line->cmd.keys.imm_int = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References Cmd::args, AsmLine::cmd, AsmLine::cur_token, CmdKeys::imm_int, CmdArgs::imm_int, IMM_INT_T_PRINTF, Cmd::info, CmdInfo::is_args, Cmd::keys, maybedigit(), Status::NORMAL_WORK, ArgsEnabled::ram, String_PRINTF, String_sscanf(), THROW_SYNTAX_ERROR_, and AsmLine::tokens.
Referenced by asm_read_args_ram().
asm_read_arg_label()
Status::Statuses asm_read_arg_label (const Asm * asm_data, AsmLine * line)
Reads label.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 168 of file read.cpp.
                                                                      {
    assert(asm_data);
    assert(line);
    String* tokens = line->tokens;
    size_t* cur_token = &line->cur_token;
    if (tokens[*cur_token].len == 0 || !line->cmd.info ||
        !line->cmd.info->is_args.label || line->cmd.keys.imm_int)
            return Status::NORMAL_WORK;
    STATUS_CHECK(asm_get_label_addr(tokens[*cur_token], asm_data, line, &line->cmd.args.imm_int));
    line->cmd.keys.imm_int = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References Cmd::args, asm_get_label_addr(), AsmLine::cmd, AsmLine::cur_token, CmdKeys::imm_int, CmdArgs::imm_int, Cmd::info, CmdInfo::is_args, Cmd::keys, ArgsEnabled::label, Status::NORMAL_WORK, STATUS_CHECK, and AsmLine::tokens.
Referenced by asm_read_args().
asm_read_arg_reg()
Status::Statuses asm_read_arg_reg (const Asm * asm_data, AsmLine * line)
Reads reg argument.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 87 of file read.cpp.
                                                                    {
    assert(asm_data);
    assert(line);
    String* tokens = line->tokens;
    size_t* cur_token = &line->cur_token;
    if (tokens[*cur_token].len == 0 || !line->cmd.info ||
        !line->cmd.info->is_args.reg || line->cmd.keys.reg)
            return Status::NORMAL_WORK;
    if (isalpha(tokens[*cur_token].str[0])) {
        const RegInfo* reg = find_reg_by_name(tokens[*cur_token]);
        if (reg == nullptr) {
            if (line->cmd.info->is_args.label) //< it may be label, not reg
                return Status::NORMAL_WORK;
            THROW_SYNTAX_ERROR_("Invalid reg name \"%.*s\"",
                                String_PRINTF(tokens[*cur_token]));
        }
        line->cmd.args.reg = reg->num;
        line->cmd.keys.reg = true;
        *cur_token += 1;
    }
    return Status::NORMAL_WORK;
}
References Cmd::args, AsmLine::cmd, AsmLine::cur_token, find_reg_by_name(), Cmd::info, CmdInfo::is_args, Cmd::keys, ArgsEnabled::label, Status::NORMAL_WORK, RegInfo::num, CmdKeys::reg, CmdArgs::reg, ArgsEnabled::reg, String_PRINTF, THROW_SYNTAX_ERROR_, and AsmLine::tokens.
Referenced by asm_read_args(), and asm_read_args_ram().
asm_read_args()
Status::Statuses asm_read_args (const Asm * asm_data, AsmLine * line)
Reads command args.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 40 of file read.cpp.
                                                                 {
    assert(asm_data);
    assert(line);
    STATUS_CHECK(asm_read_args_ram(asm_data, line));
    STATUS_CHECK(asm_read_arg_reg (asm_data, line));
    STATUS_CHECK(asm_read_arg_imm_double(asm_data, line));
    STATUS_CHECK(asm_read_arg_label (asm_data, line));
    return Status::NORMAL_WORK;
}
References asm_read_arg_imm_double(), asm_read_arg_label(), asm_read_arg_reg(), asm_read_args_ram(), Status::NORMAL_WORK, and STATUS_CHECK.
Referenced by asm_parse_and_write_line().
asm_read_args_ram()
Status::Statuses asm_read_args_ram (const Asm * asm_data, AsmLine * line)
Reads ram arguments.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 53 of file read.cpp.
                                                                     {
    assert(asm_data);
    assert(line);
    String* tokens = line->tokens;
    size_t* cur_token = &line->cur_token;
    if (tokens[*cur_token].len == 0 || tokens[*cur_token].str[0] != '[')
            return Status::NORMAL_WORK;
    *cur_token += 1;
    if (!line->cmd.info->is_args.ram)
        THROW_SYNTAX_ERROR_("Command doesn't support ram args.");
    line->cmd.keys.ram = true;
    STATUS_CHECK(asm_read_arg_reg(asm_data, line));
    if (tokens[*cur_token].str != nullptr && tokens[*cur_token].len != 0 &&
        tokens[*cur_token].str[0] != ']')
            STATUS_CHECK(asm_read_arg_imm_int(asm_data, line));
    if (tokens[*cur_token].len == 0 || tokens[*cur_token].str[0] != ']')
        THROW_SYNTAX_ERROR_("Expected \"]\".");
    *cur_token += 1;
    if (tokens[*cur_token].len != 0)
        THROW_SYNTAX_ERROR_("No more arguments expected.");
    return Status::NORMAL_WORK;
}
References asm_read_arg_imm_int(), asm_read_arg_reg(), AsmLine::cmd, AsmLine::cur_token, Cmd::info, CmdInfo::is_args, Cmd::keys, Status::NORMAL_WORK, CmdKeys::ram, ArgsEnabled::ram, STATUS_CHECK, THROW_SYNTAX_ERROR_, and AsmLine::tokens.
Referenced by asm_read_args().
asm_read_cmd()
Status::Statuses asm_read_cmd (Asm * asm_data, AsmLine * line)
Reads command.
Parameters
asm_data
line
Returns
Status::Statuses
Definition at line 5 of file read.cpp.
                                                          {
    assert(asm_data);
    assert(line);
    if (line->tokens[line->cur_token].len == 0)
        return Status::NORMAL_WORK;
    line->cmd.info = find_command_by_name(line->tokens[line->cur_token]);
    if (line->cmd.info == nullptr) {
        if (!(line->tokens[line->cur_token + 1].len == 1 &&
              line->tokens[line->cur_token + 1].str[0] == ':')) { //< if not label
            THROW_SYNTAX_ERROR_("Command \"%.*s\" not found.",
                                String_PRINTF(line->tokens[line->cur_token]));
        }
        if (asm_data->pass_num == 0)
            STATUS_CHECK(asm_new_label(line->tokens[line->cur_token], asm_data->buf.capacity,
                                       asm_data, line));
        line->cur_token += 2;
        if (line->tokens[line->cur_token].len != 0)
            THROW_SYNTAX_ERROR_("Unexpected arg given.");
        return Status::NORMAL_WORK;
    }
    line->cmd.keys.num = line->cmd.info->num & CMD_BYTE_NUM_BIT_MASK;
    line->cur_token += 1;
    return Status::NORMAL_WORK;
}
References asm_new_label(), Asm::buf, Buffer::capacity, AsmLine::cmd, CMD_BYTE_NUM_BIT_MASK, AsmLine::cur_token, find_command_by_name(), Cmd::info, Cmd::keys, String::len, Status::NORMAL_WORK, CmdKeys::num, CmdInfo::num, Asm::pass_num, STATUS_CHECK, String::str, String_PRINTF, THROW_SYNTAX_ERROR_, and AsmLine::tokens.
Referenced by asm_parse_and_write_line().