assembler/src/asm/read.cpp File Reference
#include read.h
Macros
#define THROW_SYNTAX_ERROR_(...)
Functions
Status::Statuses asm_read_args (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info, JumpLabel *labels)
Reads command args.
Status::Statuses asm_read_args_ram (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info)
Reads ram arguments.
Status::Statuses asm_read_arg_reg (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info)
Reads reg argument.
Status::Statuses asm_read_arg_imm_int (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info)
Reads integer immutable argument.
Status::Statuses asm_read_arg_imm_double (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info)
Reads double immutable argument.
Status::Statuses asm_read_arg_label (String *tokens, size_t *cur_token, Cmd *cmd, const AsmInfo *asm_info, JumpLabel *labels)
Macro Definition Documentation
THROW_SYNTAX_ERROR_
#define THROW_SYNTAX_ERROR_(...)
Value:
                                                                return asm_throw_syntax_error(tokens[*cur_token], \
                                                                asm_info, \
                                                                __VA_ARGS__)
Definition at line 3 of file read.cpp.
Function Documentation
asm_read_arg_imm_double()
Status::Statuses asm_read_arg_imm_double (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info)
Reads double immutable argument.
Parameters
tokens
cur_token
cmd
asm_info
Returns
Status::Statuses
Definition at line 111 of file read.cpp.
                                                                  {
    assert(cmd);
    assert(tokens);
    assert(asm_info);
    if (!cmd->info->args.imm_double || tokens[*cur_token].len == 0 || cmd->keys.imm_double
        || !maybedigit(tokens[*cur_token].str[0]))
            return Status::NORMAL_WORK;
    int sscanf_num = 0;
    int sscanf_res = String_sscanf(tokens[*cur_token], IMM_DOUBLE_T_PRINTF "%n",
                                   &cmd->args.imm_double, &sscanf_num);
    if (sscanf_res != 1 || sscanf_num != tokens[*cur_token].len)
        THROW_SYNTAX_ERROR_("Invalid immediate argument \"%.*s\"",
                                String_PRINTF(tokens[*cur_token]));
    cmd->keys.imm_double = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References CmdInfo::args, Cmd::args, CmdKeys::imm_double, CmdArgs::imm_double, ArgsEn::imm_double, IMM_DOUBLE_T_PRINTF, Cmd::info, Cmd::keys, String::len, maybedigit(), Status::NORMAL_WORK, String_PRINTF, String_sscanf(), and THROW_SYNTAX_ERROR_.
Referenced by asm_read_args().
asm_read_arg_imm_int()
Status::Statuses asm_read_arg_imm_int (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info)
Reads integer immutable argument.
Parameters
tokens
cur_token
cmd
asm_info
Returns
Status::Statuses
Definition at line 87 of file read.cpp.
                                                               {
    assert(cmd);
    assert(tokens);
    assert(asm_info);
    if (!cmd->info->args.ram || tokens[*cur_token].len == 0 || cmd->keys.imm_int
        || !maybedigit(tokens[*cur_token].str[0]))
            return Status::NORMAL_WORK;
    int sscanf_num = 0;
    int sscanf_res = String_sscanf(tokens[*cur_token], IMM_INT_T_PRINTF "%n",
                                   &cmd->args.imm_int, &sscanf_num);
    if (sscanf_res != 1 || sscanf_num != tokens[*cur_token].len)
        THROW_SYNTAX_ERROR_("Invalid immediate argument \"%.*s\"",
                                String_PRINTF(tokens[*cur_token]));
    cmd->keys.imm_int = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References CmdInfo::args, Cmd::args, CmdKeys::imm_int, CmdArgs::imm_int, IMM_INT_T_PRINTF, Cmd::info, Cmd::keys, String::len, maybedigit(), Status::NORMAL_WORK, ArgsEn::ram, String_PRINTF, String_sscanf(), and THROW_SYNTAX_ERROR_.
Referenced by asm_read_args_ram().
asm_read_arg_label()
Status::Statuses asm_read_arg_label (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info, JumpLabel * labels)
Definition at line 135 of file read.cpp.
                                                                                {
    assert(tokens);
    assert(cur_token);
    assert(cmd);
    assert(asm_info);
    assert(labels);
    if (!cmd->info->args.label || tokens[*cur_token].len == 0 || cmd->keys.imm_int)
        return Status::NORMAL_WORK;
    STATUS_CHECK(asm_get_label_byte(labels, tokens[*cur_token], asm_info,
                                    &cmd->args.imm_int, asm_info->final_pass));
    cmd->keys.imm_int = true;
    *cur_token += 1;
    return Status::NORMAL_WORK;
}
References CmdInfo::args, Cmd::args, asm_get_label_byte(), AsmInfo::final_pass, CmdKeys::imm_int, CmdArgs::imm_int, Cmd::info, Cmd::keys, ArgsEn::label, String::len, Status::NORMAL_WORK, and STATUS_CHECK.
Referenced by asm_read_args().
asm_read_arg_reg()
Status::Statuses asm_read_arg_reg (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info)
Reads reg argument.
Parameters
tokens
cur_token
cmd
asm_info
Returns
Status::Statuses
Definition at line 59 of file read.cpp.
                                                           {
    assert(cmd);
    assert(tokens);
    assert(asm_info);
    if (!cmd->info->args.reg || tokens[*cur_token].len == 0 || cmd->keys.reg)
        return Status::NORMAL_WORK;
    if (isalpha(tokens[*cur_token].str[0])) {
        const RegInfo* reg = find_reg_by_name(tokens[*cur_token]);
        if (reg == nullptr) {
            if (cmd->info->args.label) //< it may be label, not reg
                return Status::NORMAL_WORK;
            THROW_SYNTAX_ERROR_("Invalid reg name \"%.*s\"", String_PRINTF(tokens[*cur_token]));
        }
        cmd->args.reg = reg->num;
        cmd->keys.reg = true;
        *cur_token += 1;
    }
    return Status::NORMAL_WORK;
}
References CmdInfo::args, Cmd::args, find_reg_by_name(), Cmd::info, Cmd::keys, ArgsEn::label, String::len, Status::NORMAL_WORK, CmdKeys::reg, CmdArgs::reg, ArgsEn::reg, reg, String_PRINTF, and THROW_SYNTAX_ERROR_.
Referenced by asm_read_args(), and asm_read_args_ram().
asm_read_args()
Status::Statuses asm_read_args (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info, JumpLabel * labels)
Reads command args.
Parameters
tokens
cur_token
cmd
asm_info
labels
Returns
Status::Statuses
Definition at line 7 of file read.cpp.
                                                                           {
    assert(tokens);
    assert(cur_token);
    assert(cmd);
    assert(asm_info);
    assert(labels);
    STATUS_CHECK(asm_read_args_ram (tokens, cur_token, cmd, asm_info));
    STATUS_CHECK(asm_read_arg_reg (tokens, cur_token, cmd, asm_info));
    STATUS_CHECK(asm_read_arg_imm_double(tokens, cur_token, cmd, asm_info));
    STATUS_CHECK(asm_read_arg_label (tokens, cur_token, cmd, asm_info, labels));
    return Status::NORMAL_WORK;
}
References asm_read_arg_imm_double(), asm_read_arg_label(), asm_read_arg_reg(), asm_read_args_ram(), Status::NORMAL_WORK, and STATUS_CHECK.
Referenced by asm_parse_and_write_line().
asm_read_args_ram()
Status::Statuses asm_read_args_ram (String * tokens, size_t * cur_token, Cmd * cmd, const AsmInfo * asm_info)
Reads ram arguments.
Parameters
tokens
cur_token
cmd
asm_info
Returns
Status::Statuses
Definition at line 24 of file read.cpp.
                                                            {
    assert(tokens);
    assert(cur_token);
    assert(cmd);
    assert(asm_info);
    if (tokens[*cur_token].str == nullptr || tokens[*cur_token].len == 0
        || tokens[*cur_token].str[0] != '[')
            return Status::NORMAL_WORK;
    *cur_token += 1;
    if (!cmd->info->args.ram)
        THROW_SYNTAX_ERROR_("Command doesn't support ram args.");
    cmd->keys.ram = true;
    STATUS_CHECK(asm_read_arg_reg(tokens, cur_token, cmd, asm_info));
    if (tokens[*cur_token].str != nullptr && tokens[*cur_token].len != 0
        && tokens[*cur_token].str[0] != ']')
            STATUS_CHECK(asm_read_arg_imm_int(tokens, cur_token, cmd, asm_info));
    if (tokens[*cur_token].len == 0 || tokens[*cur_token].str[0] != ']')
        THROW_SYNTAX_ERROR_("Expected \"]\".");
    *cur_token += 1;
    if (tokens[*cur_token].len != 0)
        THROW_SYNTAX_ERROR_("No more arguments expected.");
    return Status::NORMAL_WORK;
}
References CmdInfo::args, asm_read_arg_imm_int(), asm_read_arg_reg(), Cmd::info, Cmd::keys, Status::NORMAL_WORK, CmdKeys::ram, ArgsEn::ram, STATUS_CHECK, and THROW_SYNTAX_ERROR_.
Referenced by asm_read_args().