spu/src/spu.cpp File Reference
#include spu.h
Macros
#define THROW_RUNTIME_ERROR_(text)
#define DATA_GET_VAL_(dest, val_t)
#define STK_POP_AND_PUSH_ONE_(expression)
#define STK_POP_AND_PUSH_TWO_(expression)
Functions
Status::Statuses spu_parse (const char *data, const size_t size)
Parses data and executes it.
Status::Statuses spu_execute_command (SpuData *spu, const Cmd *cmd, const size_t ip)
Executes one command.
Variables
LogFileData log_file = {STACK_LOG_FILENAME}
Macro Definition Documentation
DATA_GET_VAL_
#define DATA_GET_VAL_(dest, val_t)
Value:
                                        do { \
                                        memcpy(&dest, data + cur_byte, sizeof(val_t)); \
                                        cur_byte += sizeof(val_t); \
                                    } while(0)
Definition at line 34 of file spu.cpp.
STK_POP_AND_PUSH_ONE_
#define STK_POP_AND_PUSH_ONE_(expression)
Value:
                                                                                stk_res |= stk_pop(&spu->stk, &a); \
                                                                                \
                                            if (stk_res == Stack::OK) \
                                                stk_res |= stk_push(&spu->stk, expression)
Definition at line 96 of file spu.cpp.
STK_POP_AND_PUSH_TWO_
#define STK_POP_AND_PUSH_TWO_(expression)
Value:
                                                                                stk_res |= stk_pop(&spu->stk, &b); \
                                                                                \
                                            if (stk_res != Stack::OK) break; \
                                                                                \
                                            stk_res |= stk_pop(&spu->stk, &a); \
                                                                                \
                                            if (stk_res == Stack::OK) \
                                                stk_res |= stk_push(&spu->stk, expression)
Definition at line 101 of file spu.cpp.
THROW_RUNTIME_ERROR_
#define THROW_RUNTIME_ERROR_(text)
Value:
            do { \
            fprintf(stderr, CONSOLE_RED("Runtime error occured. " text) " Byte %zu\n", ip); \
            return Status::RUNTIME_ERROR; \
        } while(0)
Definition at line 29 of file spu.cpp.
Function Documentation
spu_execute_command()
Status::Statuses spu_execute_command (SpuData * spu, const Cmd * cmd, const size_t op)
Executes one command.
Parameters
spu
cmd
op operation pointer
Returns
Status::Statuses
Definition at line 110 of file spu.cpp.
                                                                                  {
    assert(spu);
    assert(cmd);
    if (cmd->byte.ram)
        THROW_RUNTIME_ERROR_("SPU doesn't support RAM yet :-("); // FIXME
    int stk_res = Stack::OK;
    double a = NAN;
    double b = NAN;
    switch (cmd->info->num) {
        case CMD_HLT:
            return Status::OK_EXIT;
        case CMD_PUSH:
            if (!cmd->byte.reg && !cmd->byte.imm)
                THROW_RUNTIME_ERROR_("\"push\" requires at least one argument.");
            a = 0;
            if (cmd->byte.reg)
                a += spu->reg[cmd->args.reg];
            if (cmd->byte.imm)
                a += cmd->args.imm;
            stk_res |= stk_push(&spu->stk, a);
            break;
        case CMD_POP:
            if (!cmd->byte.reg)
                THROW_RUNTIME_ERROR_("\"pop\" requires reg.");
            stk_res |= stk_pop(&spu->stk, &spu->reg[cmd->args.reg]);
            break;
        case CMD_IN:
            a = spu_get_double_from_input();
            if (isnan(a))
                return Status::WRONG_USER_INPUT;
            stk_res |= stk_push(&spu->stk, a);
            break;
        case CMD_OUT:
            stk_res |= stk_pop(&spu->stk, &a);
            if (stk_res == Stack::OK)
                if (!spu_print_double(a))
                    return Status::OUTPUT_ERROR;
            break;
        case CMD_ADD:
            STK_POP_AND_PUSH_TWO_(a + b);
            break;
        case CMD_SUB:
            STK_POP_AND_PUSH_TWO_(a - b);
            break;
        case CMD_MUL:
            STK_POP_AND_PUSH_TWO_(a * b);
            break;
        case CMD_DIV:
            STK_POP_AND_PUSH_TWO_(a / b);
            break;
        case CMD_SQRT:
            STK_POP_AND_PUSH_ONE_(sqrt(a));
            break;
        case CMD_SIN:
            STK_POP_AND_PUSH_ONE_(sin(a));
            break;
        case CMD_COS:
            STK_POP_AND_PUSH_ONE_(cos(a));
            break;
        default:
            break;
    }
    if (stk_res != Stack::OK) {
        fprintf(stderr, CONSOLE_RED("Runtime error occured!") " Stack error. Byte %zu\n", ip);
        stk_print_error_to_user(stk_res);
        return Status::RUNTIME_ERROR;
    }
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, CMD_ADD, CMD_COS, CMD_DIV, CMD_HLT, CMD_IN, CMD_MUL, CMD_OUT, CMD_POP, CMD_PUSH, CMD_SIN, CMD_SQRT, CMD_SUB, CONSOLE_RED, CmdByte::imm, CmdArgs::imm, Cmd::info, Status::NORMAL_WORK, CmdInfo::num, Stack::OK, Status::OK_EXIT, Status::OUTPUT_ERROR, CmdByte::ram, CmdByte::reg, CmdArgs::reg, SpuData::reg, Status::RUNTIME_ERROR, spu_get_double_from_input(), spu_print_double(), SpuData::stk, stk_pop(), STK_POP_AND_PUSH_ONE_, STK_POP_AND_PUSH_TWO_, stk_print_error_to_user(), stk_push(), THROW_RUNTIME_ERROR_, and Status::WRONG_USER_INPUT.
Referenced by spu_parse().
spu_parse()
Status::Statuses spu_parse (const char * data, const size_t size)
Parses data and executes it.
Parameters
data
size
Returns
Status::Statuses
Definition at line 39 of file spu.cpp.
                                                              {
    assert(data);
    if (size < sizeof(SIGNATURE) || !((const Signature*) data)->check())
        return Status::SIGNATURE_ERROR;
    SpuData spu = {};
    STATUS_CHECK(spu.ctor());
    size_t cur_byte = sizeof(SIGNATURE);
    size_t ip = cur_byte; //< instruction pointer
    Cmd cmd = {};
    while (cur_byte + sizeof(cmd.byte) <= size) {
        DATA_GET_VAL_(cmd.byte, CmdByte);
        cmd.info = find_command_by_num(cmd.byte.num);
        if (cmd.info == nullptr)
            THROW_RUNTIME_ERROR_("Invalid command.");
        if (cur_byte + cmd.size() > size) {
            stk_dtor(&spu.stk);
            THROW_RUNTIME_ERROR_("Arguments not found.");
        }
        if (cmd.byte.reg)
            DATA_GET_VAL_(cmd.args.reg, RegNum_t);
        if (cmd.byte.imm) {
            if (cmd.byte.ram)
                DATA_GET_VAL_(cmd.args.imm_ram, Imm_ram_t);
            else
                DATA_GET_VAL_(cmd.args.imm, Imm_t);
        }
        Status::Statuses res = spu_execute_command(&spu, &cmd, ip);
        if (res != Status::NORMAL_WORK) {
            stk_dtor(&spu.stk);
            return res;
        }
        cmd = {};
        ip = cur_byte;
    }
    spu.dtor();
    THROW_RUNTIME_ERROR_("Program has no halt!");
    return Status::NORMAL_WORK;
}
References Cmd::args, Cmd::byte, SpuData::ctor(), DATA_GET_VAL_, SpuData::dtor(), find_command_by_num(), CmdByte::imm, CmdArgs::imm, CmdArgs::imm_ram, Cmd::info, Status::NORMAL_WORK, CmdByte::num, CmdByte::ram, CmdByte::reg, CmdArgs::reg, SIGNATURE, Status::SIGNATURE_ERROR, Cmd::size(), spu_execute_command(), STATUS_CHECK, SpuData::stk, stk_dtor(), and THROW_RUNTIME_ERROR_.
Referenced by main().
Variable Documentation
log_file
LogFileData log_file = {STACK_LOG_FILENAME}
Definition at line 3 of file spu.cpp.
Referenced by log_close_file(), log_open_file(), log_printf(), stk_dump(), and stk_print_error().