InputData Struct Reference
Specifies input text file data.
#include <text_proccessor.h>
Public Member Functions
Status::Statuses ctor (const char *filename)
void detor ()
Public Attributes
FILE * file = nullptr
char * text = nullptr
String * lines = nullptr
size_t lines_cnt = 0
Detailed Description
Specifies input text file data.
Definition at line 14 of file text_proccessor.h.
Member Function Documentation
ctor()
Status::Statuses InputData::ctor (const char * filename)
Definition at line 3 of file text_proccessor.cpp.
                                                   {
    assert(filename);
    Status::Statuses res = file_open_read_close(filename, &text, 1);
    if (res != Status::NORMAL_WORK)
        return res;
    assert(text);
    lines_cnt = cntchar(text, '\n');
    lines = (String*)calloc(lines_cnt + 1, sizeof(String));
    if (lines == nullptr) {
        printf("Memory allocation error!\n");
        return Status::MEMORY_EXCEED;
    }
    split_text_to_lines(text, lines);
    return Status::NORMAL_WORK;
}
References cntchar(), file_open_read_close(), lines, lines_cnt, Status::MEMORY_EXCEED, Status::NORMAL_WORK, split_text_to_lines(), and text.
Referenced by main().
detor()
void InputData::detor ()
Definition at line 25 of file text_proccessor.cpp.
                      {
    FREE(lines);
    FREE(text);
}
References FREE, lines, and text.
Referenced by main().
Member Data Documentation
file
FILE* InputData::file = nullptr
Definition at line 16 of file text_proccessor.h.
lines
String* InputData::lines = nullptr
Definition at line 20 of file text_proccessor.h.
Referenced by asm_do_pass(), ctor(), and detor().
lines_cnt
size_t InputData::lines_cnt = 0
Definition at line 21 of file text_proccessor.h.
Referenced by asm_do_pass(), and ctor().
text
char* InputData::text = nullptr
Definition at line 18 of file text_proccessor.h.
Referenced by ctor(), and detor().
The documentation for this struct was generated from the following files:
shared/lib/text/text_proccessor.h
shared/lib/text/text_proccessor.cpp