SpuData Struct Reference
Keeps spu structs and variables.
#include <spu.h>
Public Member Functions
Status::Statuses ctor ()
Status::Statuses dtor ()
void dump (const char *data, const size_t *cur_byte)
Public Attributes
Stack stk = {}
Imm_double_t reg [REGS_NUM] = {}
Imm_double_t * ram = nullptr
const char * header = "Processor"
sfmlWindow sfml = {}
Detailed Description
Keeps spu structs and variables.
Definition at line 35 of file spu.h.
Member Function Documentation
ctor()
Status::Statuses SpuData::ctor ()
Definition at line 5 of file spu.cpp.
                             {
    int stk_res = STK_CTOR(&stk);
    if (stk_res != Stack::OK) {
        fprintf(stderr, CONSOLE_RED("Stack initialising error\n"));
        stk_print_error_to_user(stk_res);
        return Status::RUNTIME_ERROR;
    }
    ram = (Imm_double_t*)calloc(RAM_SIZE, sizeof(Imm_double_t));
    if (!ram) {
        fprintf(stderr, CONSOLE_RED("RAM allocation error\n"));
        return Status::MEMORY_EXCEED;
    }
#ifdef GRAPHICS
    if (!sfml.ctor(PIXEL_SIZE, PIXEL_SIZE, VIDEO_WIDTH, VIDEO_HEIGHT, header)) {
        fprintf(stderr, CONSOLE_RED("sfml memory allocation error\n"));
        return Status::MEMORY_EXCEED;
    }
#endif //< #ifdef GRAPHICS
    return Status::NORMAL_WORK;
}
References CONSOLE_RED, sfmlWindow::ctor(), header, Status::MEMORY_EXCEED, Status::NORMAL_WORK, Stack::OK, PIXEL_SIZE, ram, RAM_SIZE, Status::RUNTIME_ERROR, sfml, stk, STK_CTOR, stk_print_error_to_user(), VIDEO_HEIGHT, and VIDEO_WIDTH.
Referenced by spu_parse_and_execute().
dtor()
Status::Statuses SpuData::dtor ()
Definition at line 30 of file spu.cpp.
                             {
    int stk_res = stk_dtor(&stk);
    if (stk_res != Stack::OK) {
        fprintf(stderr, CONSOLE_RED("Stack error\n"));
        stk_print_error_to_user(stk_res);
        return Status::RUNTIME_ERROR;
    }
    FREE(ram);
#ifdef GRAPHICS
    sfml.dtor();
#endif //< #ifdef GRAPHICS
    return Status::NORMAL_WORK;
}
References CONSOLE_RED, sfmlWindow::dtor(), FREE, Status::NORMAL_WORK, Stack::OK, ram, Status::RUNTIME_ERROR, sfml, stk, stk_dtor(), and stk_print_error_to_user().
Referenced by spu_parse_and_execute().
dump()
void SpuData::dump (const char * data, const size_t * cur_byte)
Definition at line 48 of file spu.cpp.
                                                           {
    printf("# spu dump():\n"
           "# \n");
    printf("# ");
    for (size_t i = MAX(0, (ssize_t)(*cur_byte - sizeof(CmdKeys)) - 10); i < *cur_byte + 10; i++)
        printf("%02hhX ", data[i]);
    printf("\n");
    printf("# %*s^\n", (int)MIN(10, *cur_byte - sizeof(CmdKeys)) * 3, "");
    printf("# %*s%zu\n", (int)MIN(10, *cur_byte - sizeof(CmdKeys)) * 3, "", *cur_byte - sizeof(CmdKeys));
    stk_data_dump(&stk);
    printf("# \n"
           "# Registers dump:\n");
    for (size_t i = 0; i < REGS_NUM; i++)
        printf("# %.*s = " IMM_DOUBLE_T_PRINTF "\n", String_PRINTF(REGS_DICT[i].name),
                                                     reg[REGS_DICT[i].num]);
    printf("# \n"
           "# dump end\n\n");
    fflush(stdout);
}
References IMM_DOUBLE_T_PRINTF, MAX, MIN, reg, REGS_DICT, REGS_NUM, stk, stk_data_dump(), and String_PRINTF.
Member Data Documentation
header
const char* SpuData::header = "Processor"
Definition at line 43 of file spu.h.
Referenced by ctor().
ram
Imm_double_t* SpuData::ram = nullptr
Definition at line 40 of file spu.h.
Referenced by ctor(), dtor(), and spu_sfml_show().
reg
Imm_double_t SpuData::reg[REGS_NUM] = {}
Definition at line 38 of file spu.h.
{}; //< registers
Referenced by dump().
sfml
sfmlWindow SpuData::sfml = {}
Definition at line 45 of file spu.h.
{}; //< sfml wrapper struct
Referenced by ctor(), dtor(), spu_sfml_set_fps(), and spu_sfml_show().
stk
Stack SpuData::stk = {}
Definition at line 36 of file spu.h.
{}; //< Stack
Referenced by ctor(), dtor(), and dump().
The documentation for this struct was generated from the following files:
spu/src/spu.h
spu/src/spu.cpp