Buffer Struct Reference
#include <buf_lib.h>
Public Member Functions
bool ctor (ssize_t init_capacity=INIT_CAPACITY)
void dtor ()
bool resize (ssize_t new_capacity)
bool cat (const char *cat, const size_t cat_size)
Public Attributes
char * data = nullptr
ssize_t capacity = 0
ssize_t size = 0
Static Public Attributes
static const size_t INIT_CAPACITY = 256
Detailed Description
Definition at line 9 of file buf_lib.h.
Member Function Documentation
cat()
bool Buffer::cat (const char * cat, const size_t cat_size)
Definition at line 34 of file buf_lib.cpp.
                                                       {
    while (capacity < size + (ssize_t)cat_size)
        if (!resize(capacity * 2))
            return false;
    memcpy(data + size, cat, cat_size);
    size += cat_size;
    return true;
}
References capacity, cat(), data, resize(), and size.
Referenced by cat().
ctor()
bool Buffer::ctor (ssize_t init_capacity = INIT_CAPACITY)
Definition at line 3 of file buf_lib.cpp.
                                       {
    assert(init_capacity > 0);
    assert(data == nullptr);
    data = (char*)calloc(init_capacity, 1);
    if (data == nullptr)
        return false;
    capacity = init_capacity;
    return true;
}
References capacity, and data.
Referenced by assemeble_and_write().
dtor()
void Buffer::dtor ()
Definition at line 16 of file buf_lib.cpp.
                  {
    FREE(data);
}
References data, and FREE.
resize()
bool Buffer::resize (ssize_t new_capacity)
Definition at line 20 of file buf_lib.cpp.
                                        {
    assert(new_capacity > 0);
    char* tmp = data;
    data = (char*)recalloc(data, capacity, new_capacity);
    if (data == nullptr) {
        data = tmp;
        return false;
    }
    capacity = new_capacity;
    return true;
}
References capacity, data, and recalloc().
Referenced by cat().
Member Data Documentation
capacity
ssize_t Buffer::capacity = 0
Definition at line 14 of file buf_lib.h.
Referenced by cat(), ctor(), and resize().
data
char* Buffer::data = nullptr
Definition at line 12 of file buf_lib.h.
Referenced by assemeble_and_write(), cat(), ctor(), dtor(), and resize().
INIT_CAPACITY
const size_t Buffer::INIT_CAPACITY = 256 [static]
Definition at line 10 of file buf_lib.h.
size
ssize_t Buffer::size = 0
Definition at line 15 of file buf_lib.h.
Referenced by asm_parse_and_write_line(), asm_write_cmd(), assemeble_and_write(), and cat().
The documentation for this struct was generated from the following files:
shared/lib/utils/buf_lib.h
shared/lib/utils/buf_lib.cpp