shared/lib/text/text_lib.cpp File Reference
#include "text_lib.h"
Macros
#define IS_TERMINATOR_(c_) (strchr(terminators, c_) != nullptr)
Functions
String String_strtok_line (char *input)
Tokenizator for lines.
String String_strtok_special (char *input, const char *delim, const char *special_delim, const char *terminators)
Works as strtok, but also finds special_delim. If found, puts it in found_special and quits.
void split_text_to_lines (char *text, String *lines_array)
Uses my_strtok_lines and writes results into array.
void split_line_with_special_delims (char *str, const char *delims, const char *special_delims, const char *terminators, String *array, const size_t array_max_size)
Splits text to array of tokens. If founds special delim, treats it as single token.
int String_sscanf (String token, const char *format,...)
Macro Definition Documentation
IS_TERMINATOR_
#define IS_TERMINATOR_(c_) (strchr(terminators, c_) != nullptr)
Definition at line 44 of file text_lib.cpp.
Referenced by String_strtok_special().
Function Documentation
split_line_with_special_delims()
void split_line_with_special_delims (char * str, const char * delims, const char * special_delims, const char * terminators, String * array, const size_t array_max_size)
Splits text to array of tokens. If founds special delim, treats it as single token.
Parameters
str
delims
special_delims
terminators
array
array_max_size
Definition at line 114 of file text_lib.cpp.
                                                                                {
    assert(str);
    assert(delims);
    assert(special_delims);
    assert(array);
    assert(array_max_size > 0);
    array[0] = String_strtok_special(str, delims, special_delims, terminators);
    for (size_t i = 1; i < array_max_size && array[i - 1].str != nullptr; i++) {
        array[i] = String_strtok_special(nullptr, delims, special_delims, terminators);
    }
}
References String::str, and String_strtok_special().
Referenced by asm_parse_and_write_line().
split_text_to_lines()
void split_text_to_lines (char * text, String * lines_array)
Uses my_strtok_lines and writes results into array.
Parameters
text
lines_array
Definition at line 103 of file text_lib.cpp.
                                                          {
    assert(text);
    assert(lines_array);
    lines_array[0] = String_strtok_line(text);
    for (size_t i = 1; lines_array[i - 1].str != nullptr; i++) {
        lines_array[i] = String_strtok_line(nullptr);
    }
}
References String::str, and String_strtok_line().
Referenced by InputData::ctor().
String_sscanf()
int String_sscanf (String token, const char * format, ...)
Definition at line 129 of file text_lib.cpp.
                                                         {
    assert(format);
    assert(token.str);
    const char tmp = token.str[token.len];
    token.str[token.len] = '\0';
    va_list arg_list = {};
    va_start(arg_list, format);
    int ret = vsscanf(token.str, format, arg_list);
    va_end(arg_list);
    token.str[token.len] = tmp;
    return ret;
}
References String::len, and String::str.
Referenced by asm_read_arg_imm_double(), and asm_read_arg_imm_int().
String_strtok_line()
String String_strtok_line (char * str)
Tokenizator for lines.
Parameters
str
Returns
String
Definition at line 3 of file text_lib.cpp.
                                       {
    static char* str = nullptr;
    if (input != nullptr)
        str = input;
    else
        input = str;
    if (str == nullptr)
        return String {};
    String ret = {};
    ret.str = str;
    while (*str && *str != '\r' && *str != '\n')
        str++;
    while (*str && (*str == '\r')) {
        if (ret.len == 0)
            ret.len = str - input;
        *str = '\0';
        str++;
    }
    if (ret.len == 0)
        ret.len = str - input;
    if (!*str) {
        str = nullptr;
        return ret;
    }
    *str = '\0';
    str++;
    if (*str == '\0')
        str = nullptr;
    return ret;
}
References String::len, and String::str.
Referenced by split_text_to_lines().
String_strtok_special()
String String_strtok_special (char * input, const char * delim, const char * special_delim, const char * terminators)
Works as strtok, but also finds special_delim. If found, puts it in found_special and quits.
Parameters
input
delim
special_delim
terminators
Returns
String
Definition at line 46 of file text_lib.cpp.
                                                      {
    static char* str = nullptr;
    static String special = {nullptr, 0};
    if (input != nullptr) {
        str = input;
        special = {nullptr, 0};
    }
    if (special.str != nullptr) {
        String ret = special;
        special = {nullptr, 0};
        return ret;
    }
    if (str == nullptr)
        return {nullptr, 0};
    while (!IS_TERMINATOR_(*str) && strchr(delim, *str) != nullptr)
        str++;
    String ret = {str, 0};
    if (!IS_TERMINATOR_(*str) && strchr(special_delim, *str) != nullptr) {
        ret = {str, 1};
        str++;
    } else {
        while (!IS_TERMINATOR_(*str) && strchr(delim, *str) == nullptr) {
            if (strchr(special_delim, *str) != nullptr) {
                special = {str, 1};
                ret.len = str - ret.str;
                str++;
                break;
            }
            str++;
        }
    }
    while (!IS_TERMINATOR_(*str) && strchr(delim, *str) != nullptr) {
        if (ret.len == 0)
            ret.len = str - ret.str;
        str++;
    }
    if (IS_TERMINATOR_(*str)) {
        if (ret.len == 0)
            ret.len = str - ret.str;
        str = nullptr;
    }
    return ret;
}
References IS_TERMINATOR_, String::len, and String::str.
Referenced by split_line_with_special_delims().