shared/lib/text/text_lib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
Classes
struct const_String
Struct to keep const string and len together.
struct String
Struct to keep string and len together.
Macros
#define String_CONST(str_) {str_, sizeof(str_) - 1}
Macros for defining const strings.
#define String_TO_const(str_) {(str_).str, (str_).len}
String to const_String.
#define String_PRINTF(str_) (int)(str_).len, (str_).str
Macros for printing String (specifier "%.*s")
Functions
String String_strtok_line (char *str)
Tokenizator for lines.
String String_strtok_special (char *input, const char *delim, const char *special_delim, const char *terminators)
Works as strtok, but also finds special_delim. If found, puts it in found_special and quits.
void split_text_to_lines (char *text, String *lines_array)
Uses my_strtok_lines and writes results into array.
void split_line_with_special_delims (char *str, const char *delims, const char *special_delims, const char *terminators, String *array, const size_t array_max_size)
Splits text to array of tokens. If founds special delim, treats it as single token.
size_t cntchar (const char *str, const char ch)
Counts ch in str.
size_t cntlines (const char *str, const size_t len)
Counts line number in str.
const char * text_throw_out_comment (char *str, const char symb=';')
Finds symb in str and replaces it with '\0'.
const char * str_skip_spaces (const char *str)
Returns pointer to first non space symbol or '\0'.
const_String String_skip_spaces (const_String s)
Returns substring without spaces at the beginning.
int String_strcmp (const_String s1, const_String s2)
strcmp for const_String (not null-terminated strings)
int String_strcasecmp (const_String s1, const_String s2)
strcasecmp for const_String (not null-terminated strings)
int String_sscanf (String token, const char *format,...) __attribute__((format(scanf
sscanf for String (not null-terminated strings)
int bool maybedigit (int c)
isdigit() with + and -
Macro Definition Documentation
String_CONST
#define String_CONST(str_) {str_, sizeof(str_) - 1}
Macros for defining const strings.
Parameters
str_
Definition at line 32 of file text_lib.h.
Referenced by asm_get_label_name().
String_PRINTF
#define String_PRINTF(str_) (int)(str_).len, (str_).str
Macros for printing String (specifier "%.*s")
Parameters
str_
Definition at line 46 of file text_lib.h.
Referenced by asm_get_label_addr(), asm_new_label(), asm_read_arg_imm_double(), asm_read_arg_imm_int(), asm_read_arg_reg(), asm_read_cmd(), asm_throw_syntax_error(), asm_write_cmd_listing(), disasm_parse(), and SpuData::dump().
String_TO_const
#define String_TO_const(str_) {(str_).str, (str_).len}
String to const_String.
Parameters
str_
Definition at line 39 of file text_lib.h.
Referenced by asm_get_label_addr(), asm_new_label(), asm_write_cmd_listing(), find_command_by_name(), and find_reg_by_name().
Function Documentation
cntchar()
size_t cntchar (const char * str, const char ch) [inline]
Counts ch in str.
Parameters
str
ch
Returns
size_t
Definition at line 97 of file text_lib.h.
                                                      {
    assert(str);
    size_t cnt = 0;
    for (size_t i = 0; str[i] != '\0'; i++)
        if (str[i] == ch)
            cnt++;
    return cnt;
}
Referenced by cntlines().
cntlines()
size_t cntlines (const char * str, const size_t len) [inline]
Counts line number in str.
Parameters
str
len
Returns
size_t
Definition at line 116 of file text_lib.h.
                                                          {
    assert(str);
    size_t cnt = cntchar(str, '\n');
    if (str[len - 1] != '\n')
        cnt++;
    return cnt;
}
References cntchar().
Referenced by InputData::ctor().
maybedigit()
int bool maybedigit (int c) [inline]
isdigit() with + and -
Parameters
c
Returns
true
false
Definition at line 246 of file text_lib.h.
                              {
    return isdigit(c) || c == '-' || c == '+';
}
Referenced by asm_read_arg_imm_double(), and asm_read_arg_imm_int().
split_line_with_special_delims()
void split_line_with_special_delims (char * str, const char * delims, const char * special_delims, const char * terminators, String * array, const size_t array_max_size)
Splits text to array of tokens. If founds special delim, treats it as single token.
Parameters
str
delims
special_delims
terminators
array
array_max_size
Definition at line 114 of file text_lib.cpp.
                                                                                {
    assert(str);
    assert(delims);
    assert(special_delims);
    assert(array);
    assert(array_max_size > 0);
    array[0] = String_strtok_special(str, delims, special_delims, terminators);
    for (size_t i = 1; i < array_max_size && array[i - 1].str != nullptr; i++) {
        array[i] = String_strtok_special(nullptr, delims, special_delims, terminators);
    }
}
References String::str, and String_strtok_special().
Referenced by asm_parse_and_write_line().
split_text_to_lines()
void split_text_to_lines (char * text, String * lines_array)
Uses my_strtok_lines and writes results into array.
Parameters
text
lines_array
Definition at line 103 of file text_lib.cpp.
                                                          {
    assert(text);
    assert(lines_array);
    lines_array[0] = String_strtok_line(text);
    for (size_t i = 1; lines_array[i - 1].str != nullptr; i++) {
        lines_array[i] = String_strtok_line(nullptr);
    }
}
References String::str, and String_strtok_line().
Referenced by InputData::ctor().
str_skip_spaces()
const char * str_skip_spaces (const char * str) [inline]
Returns pointer to first non space symbol or '\0'.
Parameters
str
Returns
const char*
Definition at line 149 of file text_lib.h.
                                                    {
    if (str == nullptr)
        return nullptr;
    while (*str != '\0' && isspace(*str)) str++;
    return str;
}
String_skip_spaces()
const_String String_skip_spaces (const_String s) [inline]
Returns substring without spaces at the beginning.
Parameters
s
Returns
const_String
Definition at line 163 of file text_lib.h.
                                                       {
    assert(s.len == 0 || s.str != nullptr);
    while (s.len > 0 && isspace(*s.str)) {
        s.str++;
        s.len--;
    }
    return s;
}
References const_String::len, and const_String::str.
Referenced by asm_write_cmd_listing().
String_sscanf()
int String_sscanf (String token, const char * format, ...)
sscanf for String (not null-terminated strings)
Parameters
token
format
...
Returns
int
String_strcasecmp()
int String_strcasecmp (const_String s1, const_String s2) [inline]
strcasecmp for const_String (not null-terminated strings)
Parameters
s1
s2
Returns
int
Definition at line 208 of file text_lib.h.
                                                               {
    assert(s1.len == 0 || s1.str);
    assert(s2.len == 0 || s2.str);
    int c1 = '\0';
    int c2 = '\0';
    while (c1 == c2 && s1.len > 0 && s2.len > 0) {
        c1 = tolower(*s1.str++);
        s1.len--;
        c2 = tolower(*s2.str++);
        s2.len--;
    }
    if ((s1.len == 0) != (s2.len == 0))
        return (int)(s1.len - s2.len);
    return c1 - c2;
}
References const_String::len, and const_String::str.
Referenced by find_command_by_name().
String_strcmp()
int String_strcmp (const_String s1, const_String s2) [inline]
strcmp for const_String (not null-terminated strings)
Parameters
s1
s2
Returns
int
Definition at line 180 of file text_lib.h.
                                                           {
    assert(s1.len == 0 || s1.str);
    assert(s2.len == 0 || s2.str);
    char c1 = '\0';
    char c2 = '\0';
    while (c1 == c2 && s1.len > 0 && s2.len > 0) {
        c1 = *s1.str++;
        s1.len--;
        c2 = *s2.str++;
        s2.len--;
    }
    if ((s1.len == 0) != (s2.len == 0))
        return (int)(s1.len - s2.len);
    return c1 - c2;
}
References const_String::len, and const_String::str.
Referenced by asm_get_label_addr(), asm_new_label(), and find_reg_by_name().
String_strtok_line()
String String_strtok_line (char * str)
Tokenizator for lines.
Parameters
str
Returns
String
Definition at line 3 of file text_lib.cpp.
                                       {
    static char* str = nullptr;
    if (input != nullptr)
        str = input;
    else
        input = str;
    if (str == nullptr)
        return String {};
    String ret = {};
    ret.str = str;
    while (*str && *str != '\r' && *str != '\n')
        str++;
    while (*str && (*str == '\r')) {
        if (ret.len == 0)
            ret.len = str - input;
        *str = '\0';
        str++;
    }
    if (ret.len == 0)
        ret.len = str - input;
    if (!*str) {
        str = nullptr;
        return ret;
    }
    *str = '\0';
    str++;
    if (*str == '\0')
        str = nullptr;
    return ret;
}
References String::len, and String::str.
Referenced by split_text_to_lines().
String_strtok_special()
String String_strtok_special (char * input, const char * delim, const char * special_delim, const char * terminators)
Works as strtok, but also finds special_delim. If found, puts it in found_special and quits.
Parameters
input
delim
special_delim
terminators
Returns
String
Definition at line 46 of file text_lib.cpp.
                                                      {
    static char* str = nullptr;
    static String special = {nullptr, 0};
    if (input != nullptr) {
        str = input;
        special = {nullptr, 0};
    }
    if (special.str != nullptr) {
        String ret = special;
        special = {nullptr, 0};
        return ret;
    }
    if (str == nullptr)
        return {nullptr, 0};
    while (!IS_TERMINATOR_(*str) && strchr(delim, *str) != nullptr)
        str++;
    String ret = {str, 0};
    if (!IS_TERMINATOR_(*str) && strchr(special_delim, *str) != nullptr) {
        ret = {str, 1};
        str++;
    } else {
        while (!IS_TERMINATOR_(*str) && strchr(delim, *str) == nullptr) {
            if (strchr(special_delim, *str) != nullptr) {
                special = {str, 1};
                ret.len = str - ret.str;
                str++;
                break;
            }
            str++;
        }
    }
    while (!IS_TERMINATOR_(*str) && strchr(delim, *str) != nullptr) {
        if (ret.len == 0)
            ret.len = str - ret.str;
        str++;
    }
    if (IS_TERMINATOR_(*str)) {
        if (ret.len == 0)
            ret.len = str - ret.str;
        str = nullptr;
    }
    return ret;
}
References IS_TERMINATOR_, String::len, and String::str.
Referenced by split_line_with_special_delims().
text_throw_out_comment()
const char * text_throw_out_comment (char * str, const char symb = ';') [inline]
Finds symb in str and replaces it with '\0'.
Parameters
str
symb
Returns
returns pointer to the comment beginning
Definition at line 133 of file text_lib.h.
                                                                            {
    assert(str);
    char* comment_beginning = strchr(str, symb);
    if (comment_beginning != nullptr)
         *comment_beginning = '\0';
    return comment_beginning + (comment_beginning == nullptr ? 0 : 1);
}