assembler/src/asm/write.cpp File Reference
#include "write.h"
Macros
#define BUF_CAT_(data_)
#define F_PRINTF_CHECK_(printf) if (printf == EOF) return Status::OUT_FILE_ERROR
#define F_WRITE_CHECK_(write) if (!write) return Status::OUT_FILE_ERROR
Functions
Status::Statuses asm_write_cmd (Asm *asm_data, const AsmLine *line, FILE *listing_file)
Writes one cmd to buf.
Status::Statuses asm_write_cmd_bin (Buffer *buf, const Cmd *cmd, const bool final_pass)
Writes one cmd to bin file.
Status::Statuses asm_write_header (Buffer *buf, FILE *listing_file, const bool final_pass)
Writes header.
Status::Statuses asm_write_header_bin (Buffer *buf, const bool final_pass)
Writes header to bin buffer.
Macro Definition Documentation
BUF_CAT_
#define BUF_CAT_(data_)
Value:
                            do { \
                            if (final_pass) { \
                                if (!buf->cat((const char*)&data_, sizeof(data_))) \
                                    return Status::MEMORY_EXCEED; \
                            } else \
                                buf->capacity += sizeof(data_); \
                            } while(0)
Definition at line 17 of file write.cpp.
#define BUF_CAT_(data_) do { \
                            if (final_pass) { \
                                if (!buf->cat((const char*)&data_, sizeof(data_))) \
                                    return Status::MEMORY_EXCEED; \
                            } else \
                                buf->capacity += sizeof(data_); \
                            } while(0)
Referenced by asm_write_cmd_bin(), and asm_write_header_bin().
F_PRINTF_CHECK_
#define F_PRINTF_CHECK_(printf) if (printf == EOF) return Status::OUT_FILE_ERROR
Definition at line 47 of file write.cpp.
F_WRITE_CHECK_
#define F_WRITE_CHECK_(write) if (!write) return Status::OUT_FILE_ERROR
Definition at line 48 of file write.cpp.
Function Documentation
asm_write_cmd()
Status::Statuses asm_write_cmd (Asm * asm_data, const AsmLine * line, FILE * listing_file)
Writes one cmd to buf.
Parameters
asm_data
line
listing_file
Returns
Status::Statuses
Definition at line 3 of file write.cpp.
                                                                                     {
    assert(asm_data);
    assert(line);
    if (asm_data->pass_num == asm_data->LAST_PASS_NUM && listing_file != nullptr)
        STATUS_CHECK(asm_write_cmd_listing(listing_file, asm_data, line));
    STATUS_CHECK(asm_write_cmd_bin(&asm_data->buf, &line->cmd,
                                    asm_data->pass_num == asm_data->LAST_PASS_NUM));
    return Status::NORMAL_WORK;
}
References asm_write_cmd_bin(), asm_write_cmd_listing(), Asm::buf, AsmLine::cmd, Asm::LAST_PASS_NUM, Status::NORMAL_WORK, Asm::pass_num, and STATUS_CHECK.
Referenced by asm_parse_and_write_line().
asm_write_cmd_bin()
Status::Statuses asm_write_cmd_bin (Buffer * buf, const Cmd * cmd, const bool final_pass)
Writes one cmd to bin file.
Parameters
buf
cmd
final_pass
Returns
Status::Statuses
Definition at line 25 of file write.cpp.
                                                                                     {
    assert(buf);
    assert(cmd);
    if (cmd->info == nullptr)
        return Status::NORMAL_WORK;
    BUF_CAT_(cmd->keys);
    if (cmd->keys.reg)
        BUF_CAT_(cmd->args.reg);
    if (cmd->keys.imm_double)
        BUF_CAT_(cmd->args.imm_double);
    if (cmd->keys.imm_int)
        BUF_CAT_(cmd->args.imm_int);
    return Status::NORMAL_WORK;
}
References Cmd::args, BUF_CAT_, CmdKeys::imm_double, CmdArgs::imm_double, CmdKeys::imm_int, CmdArgs::imm_int, Cmd::info, Cmd::keys, Status::NORMAL_WORK, CmdKeys::reg, and CmdArgs::reg.
Referenced by asm_write_cmd().
asm_write_header()
Status::Statuses asm_write_header (Buffer * buf, FILE * listing_file, const bool final_pass)
Writes header.
Parameters
buf
listing_file
final_pass
Returns
Status::Statuses
Definition at line 50 of file write.cpp.
                                                                                        {
    assert(buf);
    if (final_pass && listing_file != nullptr) {
        STATUS_CHECK(asm_write_header_listing(listing_file));
    }
    STATUS_CHECK(asm_write_header_bin(buf, final_pass)); //< Bin write after listing!!! (changes cur_byte)
    return Status::NORMAL_WORK;
}
References asm_write_header_bin(), asm_write_header_listing(), Status::NORMAL_WORK, and STATUS_CHECK.
Referenced by asm_do_pass().
asm_write_header_bin()
Status::Statuses asm_write_header_bin (Buffer * buf, const bool final_pass)
Writes header to bin buffer.
Parameters
buf
final_pass
Returns
Status::Statuses
Definition at line 62 of file write.cpp.
                                                                        {
    assert(buf);
    BUF_CAT_(FILE_HEADER);
    return Status::NORMAL_WORK;
}
References BUF_CAT_, FILE_HEADER, and Status::NORMAL_WORK.
Referenced by asm_write_header().